const euro = new Intl.NumberFormat('nl-NL',{style:'currency',currency:'EUR'});
const seed={items:[{id:'i1',name:'Canvas draagtas',sku:'CT-001',stock:24,buy:8.5,sell:19.95},{id:'i2',name:'Keramische mok',sku:'KM-012',stock:8,buy:6.25,sell:14.5},{id:'i3',name:'Notitieboek A5',sku:'NB-205',stock:16,buy:4.8,sell:12.95},{id:'i4',name:'Metalen drinkfles',sku:'DF-110',stock:5,buy:11.4,sell:27.5}],transactions:[{id:'t1',type:'outgoing',itemId:'i1',qty:3,price:19.95,party:'Studio Noord',done:false,date:'2026-08-23T09:15:00'},{id:'t2',type:'incoming',itemId:'i4',qty:15,price:10.9,party:'Supply & Co.',done:false,paid:false,date:'2026-08-22T14:30:00'},{id:'t3',type:'outgoing',itemId:'i3',qty:4,price:12.95,party:'Atelier Maan',done:true,date:'2026-08-21T11:00:00'},{id:'t4',type:'incoming',itemId:'i2',qty:10,price:6.25,party:'Klei Groothandel',done:true,paid:true,date:'2026-08-20T08:45:00'}]};
let state=structuredClone(seed);let activeFilter='all';let saveQueue=Promise.resolve();
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], item=id=>state.items.find(x=>x.id===id);
function save(){saveQueue=saveQueue.then(async()=>{const response=await fetch('/api/state',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(state)});if(!response.ok)throw new Error('Opslaan mislukt.');}).catch(()=>toast('Opslaan mislukt. Controleer de verbinding.'));return saveQueue}
async function loadState(){try{const previous=localStorage.getItem('stockroom-data');if(previous){state=JSON.parse(previous);await save();localStorage.removeItem('stockroom-data');toast('Bestaande gegevens zijn veilig overgezet.')}else{const response=await fetch('/api/state',{cache:'no-store'});if(!response.ok)throw new Error();state=await response.json()}render()}catch{toast('Voorraadgegevens konden niet worden geladen.');render()}}
function render(){const activeItems=state.items.filter(i=>!i.archived);const outgoing=state.transactions.filter(t=>t.type==='outgoing');const paidIncoming=state.transactions.filter(t=>t.type==='incoming'&&t.paid);const unpaid=outgoing.filter(t=>!t.done);const expected=state.transactions.filter(t=>t.type==='incoming'&&!t.done);const buyValue=activeItems.reduce((s,i)=>s+i.stock*i.buy,0);const sellValue=activeItems.reduce((s,i)=>s+i.stock*i.sell,0);const outgoingRevenue=outgoing.reduce((s,t)=>s+t.qty*t.price,0);const paidPurchaseCosts=paidIncoming.reduce((s,t)=>s+t.qty*t.price,0);$('#inventoryBuyValue').textContent=euro.format(buyValue);$('#inventorySellValue').textContent=euro.format(sellValue);$('#potentialProfitValue').textContent=euro.format(sellValue-buyValue);$('#inventoryUnits').textContent=`${activeItems.reduce((s,i)=>s+i.stock,0)} items op voorraad`;$('#revenueValue').textContent=euro.format(outgoingRevenue-paidPurchaseCosts);$('#outstandingValue').textContent=euro.format(unpaid.reduce((s,t)=>s+t.qty*t.price,0));$('#outstandingCount').textContent=`${unpaid.length} betaling${unpaid.length===1?'':'en'} te ontvangen`;$('#expectedCount').textContent=expected.length;$('#incomingBadge').textContent=expected.length;$('#outgoingBadge').textContent=unpaid.length;$('#unpaidSummary').textContent=unpaid.length?`${unpaid.length} order${unpaid.length===1?'':'s'} · ${euro.format(unpaid.reduce((s,t)=>s+t.qty*t.price,0))}`:'Geen openstaande betalingen';$('#undeliveredSummary').textContent=expected.length?`${expected.length} levering${expected.length===1?'':'en'} · ${expected.reduce((s,t)=>s+t.qty,0)} items`:'Geen leveringen onderweg';$('#archiveCount').textContent=state.items.filter(i=>i.archived).length;renderStock();renderActivity();renderInventory();renderTransactions();renderArchive();fillItems()}
function renderStock(){const items=state.items.filter(i=>!i.archived);const max=Math.max(...items.map(i=>i.stock),1);$('#stockList').innerHTML=items.slice(0,4).map(i=>`<div class="stock-row"><div class="item-name"><span class="item-avatar">${i.name[0]}</span><div><strong>${i.name}</strong><small>${i.sku}</small></div></div><span>${i.stock} stuks</span><div class="level"><i style="width:${i.stock/max*100}%"></i></div></div>`).join('')||'<div class="empty">Nog geen items.</div>'}
function renderActivity(){const list=[...state.transactions].sort((a,b)=>new Date(b.date)-new Date(a.date)).slice(0,4);$('#activityList').innerHTML=list.map(t=>{const i=item(t.itemId);return `<div class="activity"><span class="activity-icon">${t.type==='incoming'?'↓':'↑'}</span><div><p><strong>${t.qty}× ${i?.name||'Item'}</strong> ${t.type==='incoming'?'ingekocht':'verkocht'} aan ${t.party}</p><time>${new Date(t.date).toLocaleDateString('nl-NL',{day:'numeric',month:'short'})}</time></div></div>`}).join('')}
function renderInventory(){$('#inventoryTable').innerHTML=state.items.filter(i=>!i.archived).map(i=>`<tr><td><div class="item-name"><span class="item-avatar">${i.name[0]}</span><strong>${i.name}</strong></div></td><td>${i.sku}</td><td><span class="pill ${i.stock<8?'warn':'good'}">${i.stock} stuks</span></td><td>${euro.format(i.buy)}</td><td>${euro.format(i.sell)}</td><td><strong>${euro.format(i.stock*i.buy)}</strong></td><td><button class="delete-item" data-delete-item="${i.id}" aria-label="${i.name} verwijderen" title="Verwijderen">×</button></td></tr>`).join('')||'<tr><td colspan="7" class="empty">Nog geen items.</td></tr>'}
function renderTransactions(){['incoming','outgoing'].forEach(type=>{let tx=state.transactions.filter(t=>t.type===type).sort((a,b)=>new Date(b.date)-new Date(a.date));if(activeFilter==='pending')tx=tx.filter(t=>!t.done);if(activeFilter==='done')tx=tx.filter(t=>t.done);$(`#${type}Cards`).innerHTML=tx.map(t=>{const i=item(t.itemId);const controls=type==='incoming'?`<div class="transaction-controls"><div class="transaction-status"><span class="pill ${t.done?'good':'warn'}">${t.done?'Geleverd':'Niet geleverd'}</span><span class="pill ${t.paid?'good':'warn'}">${t.paid?'Betaald':'Niet betaald'}</span></div><div class="transaction-buttons"><button class="${t.done?'undo-button':'mark-button'}" data-toggle="${t.id}">${t.done?'Levering terugdraaien':'Markeer geleverd'}</button><button class="${t.paid?'undo-button':'mark-button'}" data-toggle-paid="${t.id}">${t.paid?'Betaling terugdraaien':'Markeer betaald'}</button></div></div>`:`<div class="transaction-controls"><span class="pill ${t.done?'good':'warn'}">${t.done?'Betaald':'Niet betaald'}</span><button class="${t.done?'undo-button':'mark-button'}" data-toggle="${t.id}">${t.done?'Betaling terugdraaien':'Markeer betaald'}</button></div>`;return `<article class="transaction-card"><div><p>${i?.name||'Onbekend item'}</p><small>${t.party} · ${new Date(t.date).toLocaleDateString('nl-NL')}</small></div><div><small>Aantal</small><strong>${t.qty} stuks</strong></div><div><small>Prijs per item</small><strong>${euro.format(t.price)}</strong></div><div><small>Totaal</small><strong>${euro.format(t.qty*t.price)}</strong></div>${controls}</article>`}).join('')||'<div class="empty">Geen transacties in deze selectie.</div>'})}
function fillItems(){const sel=$('#itemSelect');const current=sel.value;sel.innerHTML=state.items.filter(i=>!i.archived).map(i=>`<option value="${i.id}">${i.name} (${i.stock} op voorraad)</option>`).join('');if(current)sel.value=current}
function showView(id){$$('.view').forEach(v=>v.classList.toggle('active-view',v.id===id));$$('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.view===id));$('#pageTitle').textContent=id==='overview'?'Goedemorgen':id[0].toUpperCase()+id.slice(1);$('.sidebar').classList.remove('open');window.scrollTo({top:0,behavior:'smooth'})}
function openDialog(type='incoming'){setType(type);$('#transactionForm').reset();$('#quantity').value=1;setType(type);$('#transactionDialog').showModal()}
function setType(type){$('#transactionType').value=type;$$('.type-switch button').forEach(b=>b.classList.toggle('active',b.dataset.type===type));const isItem=type==='item',isIncoming=type==='incoming';$('#itemSelect').parentElement.hidden=isItem;$('#newItemFields').hidden=!isItem;$$('.transaction-fields, #partyLabel, #statusLabel').forEach(el=>el.hidden=isItem);$('#incomingPaidLabel').hidden=!isIncoming;$('#itemSelect').disabled=isItem;$$('#quantity, #price, #party, #status').forEach(el=>el.disabled=isItem);$('#incomingPaid').disabled=!isIncoming;$$('#newItemName, #newItemSku').forEach(el=>{el.disabled=!isItem;el.required=isItem});if(isItem){$('#dialogTitle').textContent='Nieuw item toevoegen'}else{$('#dialogTitle').textContent=isIncoming?'Inkoop toevoegen':'Verkoop toevoegen';$('#partyLabel').childNodes[0].textContent=isIncoming?'Leverancier':'Klant';$('#party').placeholder=isIncoming?'Naam leverancier':'Naam klant';$('#statusLabel strong').textContent=isIncoming?'Al geleverd':'Al betaald';$('#statusLabel small').textContent=isIncoming?'De voorraad wordt direct bijgewerkt.':'De betaling is al ontvangen.'}}
function submit(e){e.preventDefault();const type=$('#transactionType').value;if(type==='item'){const name=$('#newItemName').value.trim(),sku=$('#newItemSku').value.trim();if(!name||!sku)return toast('Vul een itemnaam en SKU in.');state.items.push({id:crypto.randomUUID(),name,sku,stock:0,buy:0,sell:0});toast('Item toegevoegd.')}else{const itemId=$('#itemSelect').value,qty=Number($('#quantity').value),price=Number($('#price').value),party=$('#party').value.trim(),done=$('#status').checked,paid=type==='incoming'&&$('#incomingPaid').checked;if(!itemId||!qty||!party||price<0)return toast('Controleer de ingevulde gegevens.');const i=item(itemId);state.transactions.push({id:crypto.randomUUID(),type,itemId,qty,price,party,done,paid,date:new Date().toISOString()});if(type==='incoming'&&done){i.stock+=qty;i.buy=price}if(type==='outgoing'){if(qty>i.stock)return toast('Niet genoeg voorraad voor deze verkoop.');i.stock-=qty;i.sell=price}toast(type==='incoming'?'Inkoop opgeslagen.':'Verkoop opgeslagen.')}save();render();$('#transactionDialog').close()}
function toggleTransaction(id){const t=state.transactions.find(x=>x.id===id),i=item(t.itemId);if(t.type==='incoming'){if(!t.done){i.stock+=t.qty;i.buy=t.price}else if(i.stock>=t.qty)i.stock-=t.qty;else return toast('Onvoldoende voorraad om levering terug te draaien.')}t.done=!t.done;save();render();toast(t.type==='incoming'?(t.done?'Levering ontvangen.':'Levering teruggedraaid.'):(t.done?'Betaling ontvangen.':'Betaling weer opengezet.'))}
function toggleIncomingPaid(id){const t=state.transactions.find(x=>x.id===id);if(!t||t.type!=='incoming')return;t.paid=!t.paid;save();render();toast(t.paid?'Inkoop gemarkeerd als betaald.':'Inkoopbetaling weer opengezet.')}
function removeItem(id){const i=item(id);if(!i)return;const detail=i.stock>0?` Er staan nog ${i.stock} stuks geregistreerd.`:'';if(!confirm(`${i.name} uit de voorraad verwijderen?${detail} De transactiegeschiedenis blijft bewaard.`))return;i.archived=true;save();render();toast('Item uit de voorraad verwijderd.')}
function renderArchive(){const archived=state.items.filter(i=>i.archived);$('#archiveList').innerHTML=archived.map(i=>{const tx=state.transactions.filter(t=>t.itemId===i.id);const total=tx.reduce((sum,t)=>sum+t.qty*t.price,0);return `<div class="archive-row"><div><strong>${i.name}</strong><small>${i.sku} · ${tx.length} transactie${tx.length===1?'':'s'} · ${euro.format(total)}</small></div><div class="archive-actions"><button class="restore-item" data-restore-item="${i.id}">Herstellen</button><button class="purge-item" data-purge-item="${i.id}">Definitief verwijderen</button></div></div>`}).join('')||'<div class="empty">Het archief is leeg.</div>'}
function restoreItem(id){const i=item(id);if(!i)return;i.archived=false;save();render();toast('Item hersteld.')}
function purgeItem(id){const i=item(id);if(!i)return;const tx=state.transactions.filter(t=>t.itemId===id);if(!confirm(`${i.name} definitief verwijderen? Hiermee verwijder je ook ${tx.length} gekoppelde transactie${tx.length===1?'':'s'} en de bijbehorende omzetgeschiedenis. Dit kan niet ongedaan worden gemaakt.`))return;state.transactions=state.transactions.filter(t=>t.itemId!==id);state.items=state.items.filter(x=>x.id!==id);save();render();toast('Item en volledige geschiedenis definitief verwijderd.')}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>el.classList.remove('show'),2300)}
$$('.nav-item').forEach(b=>b.onclick=()=>showView(b.dataset.view));$$('[data-go]').forEach(b=>b.onclick=()=>showView(b.dataset.go));$$('[data-add]').forEach(b=>b.onclick=()=>openDialog(b.dataset.add));$('#quickAddBtn').onclick=()=>openDialog('outgoing');$$('.type-switch button').forEach(b=>b.onclick=()=>setType(b.dataset.type));$('#transactionForm').onsubmit=submit;$('.mobile-menu').onclick=()=>$('.sidebar').classList.toggle('open');
$('#archiveBtn').onclick=()=>{$('#archiveDialog').showModal();renderArchive()};$('#closeArchiveBtn').onclick=()=>$('#archiveDialog').close();
document.addEventListener('click',e=>{const ip=e.target.closest('[data-toggle-paid]');if(ip)toggleIncomingPaid(ip.dataset.togglePaid);const p=e.target.closest('[data-purge-item]');if(p)purgeItem(p.dataset.purgeItem);const r=e.target.closest('[data-restore-item]');if(r)restoreItem(r.dataset.restoreItem);const d=e.target.closest('[data-delete-item]');if(d)removeItem(d.dataset.deleteItem);const t=e.target.closest('[data-toggle]');if(t)toggleTransaction(t.dataset.toggle);const f=e.target.closest('.filter');if(f){activeFilter=f.dataset.filter;$$('.filter').forEach(x=>x.classList.toggle('active',x===f));renderTransactions()}});
$('#exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`stockroom-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href);toast('Export gedownload.')};loadState();

