(()=>{
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fmtBytes=n=>{n=Number(n||0);if(n<1024)return`${n} B`;if(n<1024**2)return`${(n/1024).toFixed(1)} KB`;if(n<1024**3)return`${(n/1024**2).toFixed(1)} MB`;return`${(n/1024**3).toFixed(1)} GB`};
const fmtDate=v=>v?new Date(v).toLocaleString('nl-NL'):'—';
let lastData=null;
function render(data){
  lastData=data;const host=document.getElementById('platformAdmin'); if(!host||!data?.backup)return;
  let box=document.getElementById('platformBackupHealth');
  if(!box){box=document.createElement('article');box.id='platformBackupHealth';box.className='platform-backup-health';const stats=document.getElementById('platformStats');(stats?.parentNode||host).insertBefore(box,stats?.nextSibling||host.firstChild)}
  const b=data.backup,latest=b.latest_backup,restore=b.last_restore_test,backups=b.backups||[];
  const options=backups.map(x=>`<option value="${esc(x.filename)}">${esc(x.filename)} · ${fmtDate(x.created_at)} · ${fmtBytes(x.size_bytes)}</option>`).join('');
  box.innerHTML=`<div class="platform-backup-head"><div><p class="eyebrow">Databaseveiligheid</p><h3>Backup & restore</h3></div><span class="platform-status ${b.healthy?'':'suspended'}">${b.healthy?'Gezond':'Aandacht nodig'}</span></div><div class="platform-backup-grid"><div><small>Laatste backup</small><strong>${latest?fmtDate(latest.created_at):'Geen backup'}</strong><span>${latest?`${esc(latest.filename)} · ${fmtBytes(latest.size_bytes)}`:'Nog geen bestand gevonden'}</span></div><div><small>Checksum</small><strong>${latest?.checksum_exists?'Aanwezig':'Ontbreekt'}</strong><span>Retentie ${Number(b.retention_days||0)} dagen</span></div><div><small>Laatste restore-test</small><strong>${restore?fmtDate(restore.tested_at):'Niet geregistreerd'}</strong><span>${esc(restore?.details||'Nog geen succesvolle restore-test')}</span></div></div>${(b.warnings||[]).length?`<div class="platform-backup-warnings">${b.warnings.map(w=>`<div>⚠ ${esc(w)}</div>`).join('')}</div>`:''}<div class="platform-restore-controls"><label>Backupbestand<select id="platformRestoreFile" ${backups.length?'':'disabled'}>${options||'<option>Geen backups beschikbaar</option>'}</select></label><div class="platform-restore-actions"><button class="button ghost" id="platformRestoreTestBtn" type="button" ${b.restore_test_enabled&&backups.length?'':'disabled'}>Restore-test uitvoeren</button><button class="button danger" id="platformRestoreBtn" type="button" ${b.restore_enabled&&backups.length?'':'disabled'}>Database herstellen</button></div><small>${b.restore_test_enabled?'Restore-testdatabase geconfigureerd.':'RESTORE_DATABASE_URL ontbreekt voor restore-tests.'} ${b.restore_enabled?'Echte restore is ingeschakeld.':'Echte restore is uitgeschakeld; zet ALLOW_PLATFORM_RESTORE=1 en PLATFORM_RESTORE_DATABASE_URL in Coolify.'}</small></div>`;
}
async function refresh(){try{const r=await fetch('/api/platform-admin',{cache:'no-store'});if(!r.ok)return;render(await r.json())}catch{}}
async function post(url,body){const r=await fetch(url,{method:'POST',body});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Actie mislukt.');return d}
const style=document.createElement('style');style.textContent='.platform-backup-health{border:1px solid var(--line);border-radius:16px;background:var(--paper);padding:16px;margin:0 0 16px}.platform-backup-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.platform-backup-head h3{margin:2px 0 0}.platform-backup-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px;margin-top:14px}.platform-backup-grid>div{padding:12px;border-radius:12px;background:color-mix(in srgb,var(--paper) 85%,#000 3%);min-width:0}.platform-backup-grid small,.platform-backup-grid span{display:block;color:var(--muted)}.platform-backup-grid strong{display:block;margin:4px 0;overflow-wrap:anywhere}.platform-backup-warnings{margin-top:12px;display:grid;gap:6px;color:#991b1b}.platform-restore-controls{display:grid;gap:10px;margin-top:14px;padding-top:14px;border-top:1px solid var(--line)}.platform-restore-controls label{display:grid;gap:6px;font-weight:700}.platform-restore-controls select{width:100%;border:1px solid var(--line);border-radius:10px;padding:10px;background:#fff;font:inherit}.platform-restore-actions{display:flex;gap:8px;flex-wrap:wrap}.platform-restore-controls small{color:var(--muted)}@media(max-width:700px){.platform-backup-grid{grid-template-columns:1fr}.platform-backup-head{align-items:center}.platform-restore-actions{display:grid}.platform-restore-actions .button{width:100%}}';document.head.appendChild(style);
document.addEventListener('click',async e=>{if(e.target.closest('[data-view="platformAdmin"]')||e.target.id==='refreshPlatformAdmin'){setTimeout(refresh,250);return}const select=document.getElementById('platformRestoreFile');if(e.target.id==='platformRestoreTestBtn'){if(!select?.value)return;const fd=new FormData();fd.set('filename',select.value);e.target.disabled=true;try{await post('/api/platform-admin/restore-test',fd);alert('Restore-test succesvol uitgevoerd.');await refresh()}catch(err){alert(err.message)}finally{if(document.getElementById('platformRestoreTestBtn'))document.getElementById('platformRestoreTestBtn').disabled=!(lastData?.backup?.restore_test_enabled)}}if(e.target.id==='platformRestoreBtn'){if(!select?.value)return;const confirmText=prompt(`WAARSCHUWING: de doel-database wordt overschreven met ${select.value}.\n\nTyp HERSTEL om door te gaan:`,'');if(confirmText===null)return;const fd=new FormData();fd.set('filename',select.value);fd.set('confirmation',confirmText);e.target.disabled=true;try{await post('/api/platform-admin/restore',fd);alert('Database restore succesvol afgerond. Herstart de applicatie indien deze restore de productie-database betreft.');await refresh()}catch(err){alert(err.message)}finally{if(document.getElementById('platformRestoreBtn'))document.getElementById('platformRestoreBtn').disabled=!(lastData?.backup?.restore_enabled)}}});
window.addEventListener('load',()=>setTimeout(refresh,350));
})();
