(()=>{
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fmtBytes=n=>{n=Number(n||0);if(n<1024)return`${n} B`;if(n<1024**2)return`${(n/1024).toFixed(1)} KB`;if(n<1024**3)return`${(n/1024**2).toFixed(1)} MB`;return`${(n/1024**3).toFixed(1)} GB`};
const fmtDate=v=>v?new Date(v).toLocaleString('nl-NL'):'—';
function render(data){
  const host=document.getElementById('platformAdmin'); if(!host||!data?.backup)return;
  let box=document.getElementById('platformBackupHealth');
  if(!box){box=document.createElement('article');box.id='platformBackupHealth';box.className='platform-backup-health';const stats=document.getElementById('platformStats');(stats?.parentNode||host).insertBefore(box,stats?.nextSibling||host.firstChild)}
  const b=data.backup,latest=b.latest_backup,restore=b.last_restore_test;
  box.innerHTML=`<div class="platform-backup-head"><div><p class="eyebrow">Databaseveiligheid</p><h3>Backup & restore</h3></div><span class="platform-status ${b.healthy?'':'suspended'}">${b.healthy?'Gezond':'Aandacht nodig'}</span></div><div class="platform-backup-grid"><div><small>Laatste backup</small><strong>${latest?fmtDate(latest.created_at):'Geen backup'}</strong><span>${latest?`${esc(latest.filename)} · ${fmtBytes(latest.size_bytes)}`:'Nog geen bestand gevonden'}</span></div><div><small>Checksum</small><strong>${latest?.checksum_exists?'Aanwezig':'Ontbreekt'}</strong><span>Retentie ${Number(b.retention_days||0)} dagen</span></div><div><small>Laatste restore-test</small><strong>${restore?fmtDate(restore.tested_at):'Niet geregistreerd'}</strong><span>${esc(restore?.details||'Nog geen succesvolle restore-test')}</span></div></div>${(b.warnings||[]).length?`<div class="platform-backup-warnings">${b.warnings.map(w=>`<div>⚠ ${esc(w)}</div>`).join('')}</div>`:''}`;
}
async function refresh(){try{const r=await fetch('/api/platform-admin',{cache:'no-store'});if(!r.ok)return;render(await r.json())}catch{}}
const style=document.createElement('style');style.textContent='.platform-backup-health{border:1px solid var(--line);border-radius:16px;background:var(--paper);padding:16px;margin:0 0 16px}.platform-backup-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.platform-backup-head h3{margin:2px 0 0}.platform-backup-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px;margin-top:14px}.platform-backup-grid>div{padding:12px;border-radius:12px;background:color-mix(in srgb,var(--paper) 85%,#000 3%);min-width:0}.platform-backup-grid small,.platform-backup-grid span{display:block;color:var(--muted)}.platform-backup-grid strong{display:block;margin:4px 0;overflow-wrap:anywhere}.platform-backup-warnings{margin-top:12px;display:grid;gap:6px;color:#991b1b}@media(max-width:700px){.platform-backup-grid{grid-template-columns:1fr}.platform-backup-head{align-items:center}}';document.head.appendChild(style);
window.addEventListener('load',()=>setTimeout(refresh,350));document.addEventListener('click',e=>{if(e.target.closest('[data-view="platformAdmin"]')||e.target.id==='refreshPlatformAdmin')setTimeout(refresh,250)});
})();