(()=>{
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const money=v=>Number(v||0).toLocaleString('nl-NL',{style:'currency',currency:'EUR'});
  const api=async(url,options={})=>{const response=await fetch(url,{credentials:'same-origin',...options}),data=await response.json();if(!response.ok)throw new Error(data.error||'Actie mislukt.');return data};
  let transactions=[],active=null;
  function install(){const host=document.getElementById('finance');if(!host||document.getElementById('bankReconciliationPanel'))return;host.insertAdjacentHTML('beforeend',`<article id="bankReconciliationPanel" class="card"><div class="section-heading"><div><p class="eyebrow">Bank</p><h2>Bankmutaties koppelen</h2><p>Importeer CAMT.053 of MT940. Exacte matches worden verwerkt; twijfelgevallen blijven ter controle staan.</p></div></div><form id="bankImportForm" class="form-grid"><label>Bankbestand<input id="bankFile" type="file" accept=".xml,.sta,.mt940,text/plain,application/xml" required></label><button class="button" type="submit">Importeren en vergelijken</button></form><div id="bankImportResult"></div><div id="bankTransactionList"></div></article><dialog id="bankMatchDialog"><form id="bankMatchForm"><div class="section-heading"><h2>Bankmutatie toewijzen</h2><button type="button" class="button ghost" data-bank-close>Sluiten</button></div><div id="bankMatchInfo"></div><div id="bankMatchCandidates"></div><div class="button-row"><button class="button" type="submit">Toewijzing verwerken</button><button class="button ghost" type="button" data-bank-special="bank_fee">Als bankkosten</button><button class="button ghost" type="button" data-bank-special="ignore">Negeren</button></div></form></dialog>`)}
  function render(){const host=document.getElementById('bankTransactionList');if(!host)return;const open=transactions.filter(row=>row.status==='unmatched'),done=transactions.filter(row=>row.status!=='unmatched');host.innerHTML=`<div class="section-heading"><h3>Te controleren (${open.length})</h3></div>${open.length?open.map(card).join(''):'<p>Alle bankmutaties zijn verwerkt.</p>'}<details><summary>Verwerkte mutaties (${done.length})</summary>${done.map(card).join('')}</details>`}
  function card(row){const candidates=row.suggestion?.candidates||[];return `<div class="list-card"><div><strong>${row.amount>=0?'Ontvangen':'Betaald'} ${money(Math.abs(row.amount))}</strong><small>${new Date(row.booking_date).toLocaleDateString('nl-NL')} · ${esc(row.counterparty_name||row.counterparty_iban||'Onbekende tegenpartij')}</small><small>${esc(row.reference||row.description||'Geen omschrijving')}</small><span class="status-badge ${row.status==='matched'?'success':row.status==='unmatched'?'warning':''}">${esc({matched:'gekoppeld',partial:'gedeeltelijk toegewezen',unmatched:'controle nodig'}[row.status]||row.status)}</span>${row.allocations?.map(a=>`<small>${esc(a.target_type)} · ${money(a.amount)}</small>`).join('')||''}</div>${row.status==='unmatched'?`<div class="button-row">${candidates[0]?`<button class="button" data-bank-best="${row.id}">Koppel aan ${esc(candidates[0].number)}</button>`:''}<button class="button ghost" data-bank-open="${row.id}">Toewijzen</button></div>`:''}</div>`}
  function openDialog(row){active=row;document.getElementById('bankMatchInfo').innerHTML=`<p><strong>${money(Math.abs(row.amount))}</strong> · ${esc(row.reference||row.description)}</p>`;const candidates=row.suggestion?.candidates||[];document.getElementById('bankMatchCandidates').innerHTML=candidates.length?candidates.map((candidate,index)=>`<label class="list-card"><input type="checkbox" data-bank-candidate="${index}"><span><strong>${esc(candidate.number)}</strong><small>${candidate.type==='sales_invoice'?'Verkoopfactuur':candidate.type==='purchase_invoice'?'Inkoopfactuur':'SEPA-batch'} · ${money(candidate.open)} open</small></span><input data-bank-amount="${index}" type="number" min="0.01" step="0.01" max="${candidate.open}" value="${Math.min(Math.abs(row.amount),candidate.open)}"></label>`).join(''):'<p>Geen factuurvoorstel gevonden. Verwerk deze mutatie als bankkosten of negeer haar.</p>';document.getElementById('bankMatchDialog').showModal()}
  async function load(){install();transactions=(await api('/api/bank-transactions')).transactions||[];render()}
  const fileData=file=>new Promise((resolve,reject)=>{if(!file)return reject(new Error('Kies een bankbestand.'));if(file.size>5*1024*1024)return reject(new Error('Bankbestand mag maximaal 5 MB zijn.'));const reader=new FileReader();reader.onerror=()=>reject(new Error('Bankbestand kon niet worden gelezen.'));reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.readAsDataURL(file)});
  async function reconcile(row,allocations){const body=new FormData();body.set('transaction_id',row.id);body.set('allocations',JSON.stringify(allocations));await api('/api/bank-transactions/reconcile',{method:'POST',body});document.getElementById('bankMatchDialog').close();active=null;await load();document.dispatchEvent(new CustomEvent('stockroom:refresh',{detail:{view:'finance'}}))}
  document.addEventListener('submit',async event=>{try{if(event.target.id==='bankImportForm'){event.preventDefault();const file=document.getElementById('bankFile').files[0],body=new FormData();body.set('filename',file?.name||'');body.set('file_base64',await fileData(file));const result=await api('/api/bank-import',{method:'POST',body});document.getElementById('bankImportResult').textContent=`${result.imported} mutaties geïmporteerd · ${result.automaticallyMatched} automatisch gekoppeld · ${result.duplicates} duplicaten overgeslagen.`;event.target.reset();await load();return}if(event.target.id==='bankMatchForm'){event.preventDefault();const candidates=active.suggestion?.candidates||[],allocations=[...document.querySelectorAll('[data-bank-candidate]:checked')].map(input=>{const index=Number(input.dataset.bankCandidate),candidate=candidates[index];return {type:candidate.type,id:candidate.id,amount:Number(document.querySelector(`[data-bank-amount="${index}"]`).value)}});await reconcile(active,allocations)}}catch(error){alert(error.message)}});
  document.addEventListener('click',async event=>{try{if(event.target.closest('[data-bank-close]')){document.getElementById('bankMatchDialog').close();active=null;return}const open=event.target.closest('[data-bank-open]');if(open){openDialog(transactions.find(row=>row.id===open.dataset.bankOpen));return}const best=event.target.closest('[data-bank-best]');if(best){const row=transactions.find(item=>item.id===best.dataset.bankBest);await reconcile(row,[row.suggestion.candidates[0]]);return}const special=event.target.closest('[data-bank-special]');if(special&&active)await reconcile(active,[{type:special.dataset.bankSpecial,id:'',amount:Math.abs(active.amount)}])}catch(error){alert(error.message)}});
  document.addEventListener('stockroom:refresh',event=>{if(event.detail?.view==='finance')load()});install();load().catch(()=>{});
})();
