(()=>{
const euro=new Intl.NumberFormat('nl-NL',{style:'currency',currency:'EUR'});let scanMode=null,scanItemId=null,stream=null,timer=null,zxing=null,loading=null;
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function inject(){
 const newFields=document.getElementById('newItemFields');if(newFields&&!document.getElementById('newItemBarcode')){const row=document.createElement('div');row.className='field-grid';row.innerHTML='<label>Barcode / EAN<input id="newItemBarcode" inputmode="numeric" placeholder="Scan of voer barcode in"></label><label>&nbsp;<button class="button ghost" id="scanNewItemBarcode" type="button">▣ Scan barcode</button></label>';newFields.appendChild(row)}
 const panel=document.getElementById('barcodePanel');if(panel&&!panel.querySelector('[data-scan-advice]')){panel.querySelector('p')?.insertAdjacentHTML('afterend','<button class="button ghost" data-scan-advice type="button" style="margin:0 0 12px">▣ Barcode scannen en toevoegen</button>')}
 const form=document.getElementById('transactionForm');if(form&&!document.getElementById('paymentMethodLabel')){const label=document.createElement('label');label.id='paymentMethodLabel';label.className='transaction-fields';label.innerHTML='Betaalmethode<select id="paymentMethod"><option value="bank">Online / bank</option><option value="cash">Cash</option><option value="unpaid">Nog niet betaald</option></select>';document.getElementById('incomingPaidLabel')?.insertAdjacentElement('afterend',label)}
 if(!document.getElementById('paymentAnalytics')){const host=document.getElementById('analyticsContent');if(host){const p=document.createElement('article');p.id='paymentAnalytics';p.className='panel';p.innerHTML='<div class="panel-head"><div><p class="eyebrow">Betalingen</p><h3>Cash & bank</h3></div></div><div id="paymentAnalyticsGrid" class="payment-grid"></div>';host.appendChild(p);const s=document.createElement('style');s.textContent='.payment-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.payment-grid>div{padding:15px;border:1px solid #edf0ed;border-radius:14px;background:#fafbfa}.payment-grid small{display:block;color:#6d756f;margin-bottom:7px}.payment-grid strong{font-size:20px}.payment-grid span{display:block;color:#6d756f;font-size:12px;margin-top:5px}@media(max-width:760px){.payment-grid{grid-template-columns:1fr 1fr}}@media(max-width:440px){.payment-grid{grid-template-columns:1fr}}';document.head.appendChild(s)}}
}
function stop(){if(timer)clearInterval(timer);timer=null;if(stream)stream.getTracks().forEach(t=>t.stop());stream=null;if(zxing){try{zxing.stop()}catch{}zxing=null}}
function loadZX(){if(window.ZXingBrowser?.BrowserMultiFormatReader)return Promise.resolve(window.ZXingBrowser);if(loading)return loading;loading=new Promise((ok,no)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/@zxing/browser@0.1.5/umd/zxing-browser.min.js';s.async=true;s.onload=()=>ok(window.ZXingBrowser);s.onerror=no;document.head.appendChild(s)});return loading}
async function applyBarcode(raw){const value=String(raw||'').trim();if(!value)return;stop();if(scanMode==='new'){const input=document.getElementById('newItemBarcode');if(input)input.value=value}else if(scanMode==='advice'){const state=await fetch('/api/state',{cache:'no-store'}).then(r=>r.json());const existing=(state.items||[]).find(i=>String(i.barcode||'').trim()===value);if(existing){document.querySelector(`[data-barcode-row="${CSS.escape(existing.id)}"]`)?.scrollIntoView({block:'center'});alert(`Barcode is al gekoppeld aan ${existing.name}.`)}else{const rows=[...document.querySelectorAll('[data-barcode-row]')];const target=scanItemId?rows.find(r=>r.dataset.barcodeRow===scanItemId):rows.find(r=>!r.querySelector('[data-barcode-input]')?.value.trim());if(target){target.querySelector('[data-barcode-input]').value=value;target.scrollIntoView({block:'center'});target.querySelector('[data-barcode-input]').focus()}else alert('Kies eerst het artikel waaraan je deze barcode wilt koppelen.')}}document.getElementById('barcodeScannerDialog')?.close()}
async function scan(mode,itemId=null){scanMode=mode;scanItemId=itemId;stop();const d=document.getElementById('barcodeScannerDialog'),v=document.getElementById('barcodeVideo'),status=document.getElementById('barcodeScannerStatus');if(!d||!v)return;if(!d.open)d.showModal();if(status)status.textContent='Sta cameratoegang toe…';try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});if('BarcodeDetector'in window){const detector=new BarcodeDetector({formats:['ean_13','ean_8','upc_a','upc_e','code_128','code_39','itf']});v.srcObject=stream;await v.play();timer=setInterval(async()=>{try{const c=await detector.detect(v);if(c[0]?.rawValue)applyBarcode(c[0].rawValue)}catch{}},250)}else{stream.getTracks().forEach(t=>t.stop());stream=null;const Z=await loadZX();const reader=new Z.BrowserMultiFormatReader();zxing=await reader.decodeFromVideoDevice(undefined,v,r=>{if(r)applyBarcode(typeof r.getText==='function'?r.getText():r.text)})}if(status)status.textContent='Richt de camera op de barcode.'}catch(e){stop();if(status)status.textContent='Camera kon niet starten. Voer de barcode handmatig in.'}}
async function paymentAnalytics(){const grid=document.getElementById('paymentAnalyticsGrid');if(!grid)return;try{const state=await fetch('/api/state',{cache:'no-store'}).then(r=>r.json());const tx=(state.transactions||[]).filter(t=>t.type==='outgoing'&&t.done);const sum=m=>tx.filter(t=>(t.paymentMethod||'bank')===m).reduce((s,t)=>s+Number(t.qty||0)*Number(t.price||0),0);const count=m=>tx.filter(t=>(t.paymentMethod||'bank')===m).length;const bank=sum('bank'),cash=sum('cash'),other=tx.filter(t=>!['bank','cash'].includes(t.paymentMethod||'bank')).reduce((s,t)=>s+Number(t.qty||0)*Number(t.price||0),0),total=bank+cash+other;grid.innerHTML=`<div><small>Bank</small><strong>${euro.format(bank)}</strong><span>${count('bank')} betalingen</span></div><div><small>Cash</small><strong>${euro.format(cash)}</strong><span>${count('cash')} betalingen</span></div><div><small>Overig / factuur</small><strong>${euro.format(other)}</strong></div><div><small>Totaal betalingen</small><strong>${euro.format(total)}</strong><span>${tx.length} transacties</span></div>`}catch{grid.textContent='Betalingsanalytics konden niet worden geladen.'}}
function syncPayment(){const type=document.getElementById('transactionType')?.value,label=document.getElementById('paymentMethodLabel'),select=document.getElementById('paymentMethod');if(!label||!select)return;label.hidden=type==='item';const status=document.getElementById('status'),paid=document.getElementById('incomingPaid');if(type==='incoming')select.value=paid?.checked?'bank':'unpaid';else if(type==='outgoing')select.value=status?.checked?'bank':'unpaid'}
function persistPayment(){const type=document.getElementById('transactionType')?.value,method=document.getElementById('paymentMethod')?.value;if(!method||type==='item')return;const status=document.getElementById('status'),paid=document.getElementById('incomingPaid');if(type==='incoming'&&paid)paid.checked=method!=='unpaid';if(type==='outgoing'&&status)status.checked=method!=='unpaid';window.__stockroomPendingPaymentMethod=method}
document.addEventListener('click',e=>{inject();const n=e.target.closest('#scanNewItemBarcode');if(n){e.preventDefault();scan('new');return}const a=e.target.closest('[data-scan-advice]');if(a){e.preventDefault();const id=prompt('Optioneel: voer het artikel-ID niet in; scan en kies daarna de lege barcoderegel.');scan('advice',id||null);return}if(e.target.closest('[data-view="analytics"], [data-go="analytics"]'))setTimeout(paymentAnalytics,0);if(e.target.closest('[data-type]'))setTimeout(syncPayment,0);if(e.target.closest('#saveTransaction'))persistPayment()});
document.addEventListener('change',e=>{if(e.target?.id==='paymentMethod')persistPayment()});document.addEventListener('submit',e=>{if(e.target?.id==='transactionForm'){persistPayment();setTimeout(paymentAnalytics,250)}});window.addEventListener('load',()=>{inject();syncPayment();paymentAnalytics()});
})();