(()=>{
  const money=value=>Number(value||0).toLocaleString('nl-NL',{style:'currency',currency:'EUR'});
  const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const api=async(url,options={})=>{const response=await fetch(url,{credentials:'same-origin',...options}),data=await response.json();if(!response.ok)throw new Error(data.error||'Actie mislukt.');return data};
  const now=new Date();let data=null,role='member';
  function install(){const host=document.getElementById('analyticsContent')||document.getElementById('finance');if(!host||document.getElementById('budgetPlanningPanel'))return;host.insertAdjacentHTML('beforeend',`<article id="budgetPlanningPanel" class="card"><div class="section-heading"><div><p class="eyebrow">Sturing</p><h2>Budget en afwijkingen</h2><p>Vergelijk maandbudgetten met de werkelijke cijfers en de verwachting voor het einde van de maand.</p></div><form id="budgetPeriodForm" class="button-row"><input name="year" type="number" min="2000" max="2100" value="${now.getFullYear()}" aria-label="Jaar"><select name="month" aria-label="Maand">${Array.from({length:12},(_,i)=>`<option value="${i+1}" ${i===now.getMonth()?'selected':''}>${new Date(2020,i,1).toLocaleDateString('nl-NL',{month:'long'})}</option>`).join('')}</select><button class="button" type="submit">Tonen</button></form></div><div id="budgetAlerts"></div><div id="budgetMetrics"></div><div id="budgetEditor"></div></article>`)}
  function card(key,label){const metric=data.metrics[key],good=metric.favorable?'success-text':'danger-text',forecastGood=metric.forecastFavorable?'success-text':'danger-text',link=data.links[key];return `<div class="metric"><span>${label}</span><strong>${money(metric.actual)} / ${money(metric.target)}</strong><small class="${good}">${metric.variance>=0?'+':'−'} ${money(Math.abs(metric.variance))} werkelijk t.o.v. budget</small><small class="${forecastGood}">Verwachting: ${money(metric.forecast)} (${metric.forecastVariance>=0?'+':'−'} ${money(Math.abs(metric.forecastVariance))})</small><button class="text-button" type="button" data-budget-go="${link.view}" data-budget-anchor="${link.anchor||''}">${esc(link.label)} →</button></div>`}
  function render(){if(!data)return;document.getElementById('budgetAlerts').innerHTML=data.alerts.map(item=>`<div class="notice ${item.severity}">${esc(item.message)}</div>`).join('')||'<div class="notice success">De maandverwachting ligt binnen alle ingestelde budgetten.</div>';document.getElementById('budgetMetrics').innerHTML=`<div class="metric-grid">${card('revenue','Omzet')}${card('grossProfit','Brutomarge')}${card('operatingExpenses','Bedrijfskosten')}</div><p><small>Prognose op basis van ${data.period.daysElapsed} van ${data.period.daysTotal} dagen.</small></p>`;document.getElementById('budgetEditor').innerHTML=['owner','admin'].includes(role)?`<details ${data.alerts.some(x=>x.metric==='budget')?'open':''}><summary>Maandbudget instellen</summary><form id="monthlyBudgetForm" class="form-grid"><input type="hidden" name="year" value="${data.period.year}"><input type="hidden" name="month" value="${data.period.month}"><label>Omzetbudget<input name="revenue_target" type="number" min="0" step="0.01" value="${data.budget.revenue}" required></label><label>Brutomargebudget<input name="gross_profit_target" type="number" min="0" step="0.01" value="${data.budget.grossProfit}" required></label><label>Maximale bedrijfskosten<input name="expense_limit" type="number" min="0" step="0.01" value="${data.budget.operatingExpenses}" required></label><button class="button" type="submit">Budget opslaan</button></form></details>`:''}
  async function load(){install();const form=document.getElementById('budgetPeriodForm');if(!form)return;const query=new URLSearchParams(new FormData(form));const [me,result]=await Promise.all([api('/api/me'),api('/api/budget-overview?'+query)]);role=me.stockroom?.role||'member';data=result;render()}
  document.addEventListener('submit',async event=>{try{if(event.target.id==='budgetPeriodForm'){event.preventDefault();await load()}else if(event.target.id==='monthlyBudgetForm'){event.preventDefault();await api('/api/monthly-budget',{method:'POST',body:new FormData(event.target)});await load()}}catch(error){alert(error.message)}});
  document.addEventListener('click',event=>{const button=event.target.closest('[data-budget-go]');if(!button)return;const target=document.querySelector(`[data-view="${button.dataset.budgetGo}"]`);target?.click();if(button.dataset.budgetAnchor)setTimeout(()=>document.getElementById(button.dataset.budgetAnchor)?.scrollIntoView({behavior:'smooth'}),100)});
  document.addEventListener('stockroom:refresh',event=>{if(event.detail?.view==='analytics')load().catch(()=>{})});install();load().catch(()=>{});
})();
