(() => {
  const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  let state={items:[]}, me=null, searchTimer=null;
  async function json(url,options={}){const r=await fetch(url,{cache:'no-store',...options});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Actie mislukt.');return d}

  function install(){
    const top=document.querySelector('.top-actions');
    if(top&&!document.getElementById('globalSearch')) top.insertAdjacentHTML('afterbegin','<div class="global-search-wrap"><input id="globalSearch" placeholder="Zoek artikel, SKU, barcode, klant, leverancier, order…" autocomplete="off"><div id="globalSearchResults" class="global-search-results" hidden></div></div>');
    const inventory=document.getElementById('inventory');
    const table=inventory?.querySelector('.table-card');
    if(inventory&&table&&!document.getElementById('locationPanel')){
      const panel=document.createElement('article');panel.id='locationPanel';panel.className='panel';panel.innerHTML='<div class="panel-head"><div><p class="eyebrow">Magazijnindeling</p><h3>Voorraadlocaties</h3></div><a class="button ghost" href="/api/documents/inventory.pdf" target="_blank" rel="noopener">PDF voorraadlijst</a></div><div id="locationList"></div>';inventory.insertBefore(panel,table);
    }
    if(!document.getElementById('businessToolsStyle')){const s=document.createElement('style');s.id='businessToolsStyle';s.textContent=`.global-search-wrap{position:relative;min-width:min(420px,42vw)}#globalSearch{width:100%;border:1px solid var(--line);border-radius:10px;padding:10px 12px;font:inherit;background:#fff}.global-search-results{position:absolute;z-index:80;top:calc(100% + 6px);left:0;right:0;background:#fff;border:1px solid var(--line);box-shadow:0 14px 30px rgba(0,0,0,.12);border-radius:12px;max-height:360px;overflow:auto}.global-result{display:block;width:100%;text-align:left;border:0;border-bottom:1px solid var(--line);background:#fff;padding:10px 12px;cursor:pointer}.global-result:last-child{border-bottom:0}.global-result strong,.global-result small{display:block}.global-result small{color:var(--muted);margin-top:2px}.location-grid{display:grid;grid-template-columns:minmax(160px,1fr) 140px 140px 1fr auto;gap:8px;align-items:center;padding:9px 0;border-top:1px solid var(--line)}.location-grid input{border:1px solid var(--line);border-radius:8px;padding:8px;font:inherit;width:100%}.order-pdf-btn{margin-left:6px}@media(max-width:800px){.global-search-wrap{min-width:0;flex:1}.top-actions{flex-wrap:wrap}.location-grid{grid-template-columns:1fr 1fr}.location-grid strong{grid-column:1/-1}.location-grid .location-save{grid-column:1/-1}}`;document.head.appendChild(s)}
  }

  function locationValue(item){return [item.aisle,item.shelf,item.bin].filter(Boolean).join(' / ')||item.location||''}
  function renderLocations(){const el=document.getElementById('locationList');if(!el)return;const items=(state.items||[]).filter(i=>!i.archived);el.innerHTML=items.length?items.map(i=>`<div class="location-grid" data-location-item="${esc(i.id)}"><strong>${esc(i.name)}<small>${esc(i.sku||'')}</small></strong><input data-field="aisle" placeholder="Stelling" value="${esc(i.aisle||'')}"><input data-field="shelf" placeholder="Vak" value="${esc(i.shelf||'')}"><input data-field="bin" placeholder="Bak / locatie" value="${esc(i.bin||i.location||'')}"><button class="button ghost location-save" data-save-location="${esc(i.id)}" type="button">Opslaan</button></div>`).join(''):'<small>Nog geen artikelen.</small>'}
  async function saveLocation(id,row){const latest=await json('/api/state');const item=(latest.items||[]).find(i=>String(i.id)===String(id));if(!item)throw new Error('Artikel niet gevonden.');['aisle','shelf','bin'].forEach(k=>item[k]=row.querySelector(`[data-field="${k}"]`).value.trim());item.location=[item.aisle,item.shelf,item.bin].filter(Boolean).join(' / ');const r=await fetch('/api/state',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(latest)});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Locatie opslaan mislukt.');state=latest;renderLocations()}

  function enhanceOrders(){document.querySelectorAll('.order-card').forEach(card=>{if(card.querySelector('.order-pdf-btn'))return;const select=card.querySelector('[data-order-status]');const del=card.querySelector('[data-delete-order]');const id=select?.dataset.orderStatus||del?.dataset.deleteOrder;if(!id)return;const btn=document.createElement('a');btn.className='button ghost order-pdf-btn';btn.textContent='PDF';btn.href=`/api/documents/order.pdf?id=${encodeURIComponent(id)}`;btn.target='_blank';btn.rel='noopener';(select?.parentElement||card).appendChild(btn)})}

  function showSearch(results){const box=document.getElementById('globalSearchResults');if(!box)return;if(!results.length){box.innerHTML='<div class="global-result"><small>Geen resultaten</small></div>';box.hidden=false;return}box.innerHTML=results.map(r=>`<button class="global-result" type="button" data-result-type="${esc(r.type)}" data-result-id="${esc(r.id)}"><strong>${esc(r.title)}</strong><small>${esc(r.subtitle||'')}</small></button>`).join('');box.hidden=false}
  async function runSearch(q){if(q.trim().length<2){document.getElementById('globalSearchResults').hidden=true;return}try{showSearch((await json(`/api/search?q=${encodeURIComponent(q)}`)).results||[])}catch{}}
  function openResult(type,id){const box=document.getElementById('globalSearchResults');if(box)box.hidden=true;if(type==='item'){document.querySelector('[data-view="inventory"]')?.click();setTimeout(()=>document.querySelector(`[data-item-row="${CSS.escape(id)}"]`)?.scrollIntoView({behavior:'smooth',block:'center'}),120)}else if(type==='order'){document.querySelector('[data-view="orders"]')?.click()}else{document.querySelector('[data-view="relations"]')?.click()}}

  document.addEventListener('input',e=>{if(e.target.id!=='globalSearch')return;clearTimeout(searchTimer);searchTimer=setTimeout(()=>runSearch(e.target.value),180)});
  document.addEventListener('click',async e=>{const save=e.target.closest('[data-save-location]');if(save){try{await saveLocation(save.dataset.saveLocation,save.closest('[data-location-item]'))}catch(err){alert(err.message)}return}const result=e.target.closest('[data-result-type]');if(result){openResult(result.dataset.resultType,result.dataset.resultId);return}if(!e.target.closest('.global-search-wrap')){const box=document.getElementById('globalSearchResults');if(box)box.hidden=true}});
  const obs=new MutationObserver(()=>enhanceOrders());
  window.addEventListener('load',async()=>{install();obs.observe(document.body,{childList:true,subtree:true});try{me=await json('/api/me');state=await json('/api/state');renderLocations();enhanceOrders();if(!me.permissions?.manageItems)document.getElementById('locationPanel')?.querySelectorAll('input,button').forEach(x=>x.disabled=true)}catch{}});
})();
