(()=>{
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const money=v=>Number(v||0).toLocaleString('nl-NL',{style:'currency',currency:'EUR'});
  const api=async(url,options={})=>{const response=await fetch(url,{credentials:'same-origin',...options}),data=await response.json();if(!response.ok)throw new Error(data.error||'Actie mislukt.');return data};
  let data=null,role='member',scenario='expected';
  function install(){const host=document.getElementById('finance');if(!host||document.getElementById('cashflowPanel'))return;host.insertAdjacentHTML('beforeend',`<article id="cashflowPanel" class="card"><div class="section-heading"><div><p class="eyebrow">Vooruitblik</p><h2>Kasstroomprognose</h2><p>Verwacht banksaldo op basis van facturen, betaalbatches, inkooporders en historische kosten.</p></div><div class="button-row"><button class="button ghost" data-cash-scenario="conservative">Conservatief</button><button class="button" data-cash-scenario="expected">Verwacht</button><button class="button ghost" data-cash-scenario="optimistic">Optimistisch</button></div></div><div id="cashflowSettings"></div><div id="cashflowAlerts"></div><div id="cashflowSummary"></div><div id="cashflowChart"></div><div id="cashflowEvents"></div></article>`)}
  function chart(points){const width=900,height=220,values=points.map(x=>x.balance),min=Math.min(...values,0),max=Math.max(...values,0),span=max-min||1,path=points.map((point,index)=>`${index?'L':'M'} ${(index/(points.length-1)*width).toFixed(1)} ${(height-(point.balance-min)/span*height).toFixed(1)}`).join(' '),zero=(height-(0-min)/span*height).toFixed(1);return `<svg viewBox="0 0 ${width} ${height}" role="img" aria-label="Verwacht saldo over 90 dagen" style="width:100%;height:auto"><line x1="0" y1="${zero}" x2="${width}" y2="${zero}" stroke="currentColor" opacity=".25"/><path d="${path}" fill="none" stroke="var(--primary,#2563eb)" stroke-width="5"/><text x="4" y="18" fill="currentColor">${esc(money(max))}</text><text x="4" y="${height-5}" fill="currentColor">${esc(money(min))}</text></svg>`}
  function render(){const settings=document.getElementById('cashflowSettings'),alerts=document.getElementById('cashflowAlerts'),summary=document.getElementById('cashflowSummary'),chartHost=document.getElementById('cashflowChart'),events=document.getElementById('cashflowEvents'),selected=data.scenarios[scenario];settings.innerHTML=['owner','admin'].includes(role)?`<details ${data.settings.configured?'':'open'}><summary>Saldo en veiligheidsbuffer</summary><form id="cashflowSettingsForm" class="form-grid"><label>Actueel banksaldo<input name="current_balance" type="number" step="0.01" value="${data.settings.current_balance}" required></label><label>Peildatum<input name="balance_date" type="date" value="${String(data.settings.balance_date).slice(0,10)}" required></label><label>Minimale buffer<input name="minimum_buffer" type="number" min="0" step="0.01" value="${data.settings.minimum_buffer}"></label><button class="button" type="submit">Saldo opslaan</button></form></details>`:'';alerts.innerHTML=data.alerts.map(item=>`<div class="notice ${item.severity}">${esc(item.message)}</div>`).join('');summary.innerHTML=`<div class="metric-grid">${[30,60,90].map(days=>`<div class="metric"><span>Saldo na ${days} dagen</span><strong>${money(selected[String(days)].endingBalance)}</strong><small>${money(selected[String(days)].incoming)} in · ${money(selected[String(days)].outgoing)} uit</small></div>`).join('')}</div><p><small>${esc(data.assumptions[scenario])}</small></p>`;chartHost.innerHTML=chart(selected['90'].points);events.innerHTML=`<details><summary>Verwachte kasstromen (${data.events.length})</summary>${data.events.map(event=>`<div class="list-card"><span>${new Date(event.date).toLocaleDateString('nl-NL')} · ${event.direction==='in'?'+':'−'} ${money(event.amount)} · ${esc(event.label)}</span><small>${esc({sales_invoice:'Verkoopfactuur',purchase_invoice:'Inkoopfactuur',payment_batch:'Betaalbatch',purchase_order:'Nog niet gefactureerde inkooporder',recurring_costs:'Historische kostenschatting'}[event.kind]||event.kind)}</small></div>`).join('')||'<p>Geen verwachte kasstromen.</p>'}</details>`;document.querySelectorAll('[data-cash-scenario]').forEach(button=>{button.classList.toggle('ghost',button.dataset.cashScenario!==scenario)})}
  async function load(){install();const [me,result]=await Promise.all([api('/api/me'),api('/api/cashflow-forecast')]);role=me.stockroom?.role||'member';data=result;render()}
  document.addEventListener('click',event=>{const button=event.target.closest('[data-cash-scenario]');if(button){scenario=button.dataset.cashScenario;render()}});
  document.addEventListener('submit',async event=>{if(event.target.id!=='cashflowSettingsForm')return;event.preventDefault();try{await api('/api/cashflow-settings',{method:'POST',body:new FormData(event.target)});await load()}catch(error){alert(error.message)}});
  document.addEventListener('stockroom:refresh',event=>{if(event.detail?.view==='analytics')load()});install();load().catch(()=>{});
})();
