(()=>{
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
async function api(url,options={}){const r=await fetch(url,{cache:'no-store',...options});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Actie mislukt.');return d}
async function fileData(file){if(!file)return'';if(file.size>250000)throw new Error('Logo is te groot. Gebruik een PNG/JPEG kleiner dan 250 KB.');return await new Promise((res,rej)=>{const fr=new FileReader();fr.onload=()=>res(fr.result);fr.onerror=rej;fr.readAsDataURL(file)})}
function installSettings(){const settings=document.getElementById('settings');if(!settings||document.getElementById('documentV3Panel'))return;const grid=settings.querySelector('.settings-grid');if(!grid)return;const panel=document.createElement('article');panel.id='documentV3Panel';panel.className='settings-panel';panel.innerHTML=`<h3>Documenten & facturen</h3><p>Huisstijl, btw en betaalgegevens voor facturen, pakbonnen en retourdocumenten.</p><form id="documentV3Form"><div class="docv3-grid"><label>Logo<input id="docLogo" type="file" accept="image/png,image/jpeg"></label><label>Huisstijlkleur<input name="accent_hex" type="color" value="#111827"></label><label>IBAN<input name="iban" placeholder="NL00 BANK 0000 0000 00"></label><label>BIC<input name="bic" placeholder="BANKNL2A"></label><label>Betaaltermijn (dagen)<input name="payment_term_days" type="number" min="0" max="365" value="14"></label><label>Standaard BTW %<input name="default_vat_percent" type="number" min="0" max="100" step="0.001" value="21"></label><label class="docv3-wide">Factuurtekst/footer<textarea name="invoice_footer" rows="3"></textarea></label></div><div class="docv3-actions"><button class="button primary" type="submit">Documentinstellingen opslaan</button><button class="button ghost" id="removeDocLogo" type="button">Logo verwijderen</button></div><small id="docLogoStatus"></small></form>`;grid.appendChild(panel);if(!document.getElementById('docV3SettingsStyle')){const st=document.createElement('style');st.id='docV3SettingsStyle';st.textContent='.docv3-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.docv3-grid label{display:grid;gap:5px}.docv3-grid input,.docv3-grid textarea{border:1px solid var(--line);border-radius:9px;padding:9px 10px;font:inherit}.docv3-wide{grid-column:1/-1}.docv3-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}@media(max-width:700px){.docv3-grid{grid-template-columns:1fr}.docv3-wide{grid-column:auto}}';document.head.appendChild(st)}}
async function loadSettings(){installSettings();const form=document.getElementById('documentV3Form');if(!form)return;try{const d=await api('/api/documents/settings');['iban','bic','payment_term_days','default_vat_percent','invoice_footer','accent_hex'].forEach(k=>{if(form.elements[k]&&d[k]!==undefined)form.elements[k].value=d[k]??''});document.getElementById('docLogoStatus').textContent=d.logo_configured?'Logo ingesteld':'Geen logo ingesteld'}catch(e){document.getElementById('docLogoStatus').textContent=e.message}}
function enhanceOrders(){document.querySelectorAll('#orders .order-card').forEach(card=>{if(card.querySelector('.doc-v3-actions'))return;const status=card.querySelector('[data-order-status]');const del=card.querySelector('[data-delete-order]');const id=status?.dataset.orderStatus||del?.dataset.deleteOrder;if(!id)return;const type=status?.dataset.orderType||del?.dataset.orderType||'',recipient=card.dataset.relationEmail||'';const wrap=document.createElement('div');wrap.className='doc-v3-actions';wrap.innerHTML=`${type==='sales'?`<button class="button ghost" type="button" data-doc-preview="invoice" data-order-id="${esc(id)}">Preview factuur</button><button class="button primary" type="button" data-doc-mail="invoice" data-order-id="${esc(id)}" data-recipient="${esc(recipient)}">Mail factuur</button>`:''}<button class="button ghost" type="button" data-doc-mail="packing" data-order-id="${esc(id)}" data-recipient="${esc(recipient)}">Mail pakbon</button><button class="button ghost" type="button" data-doc-mail="return" data-order-id="${esc(id)}" data-recipient="${esc(recipient)}">Mail retour</button>`;card.appendChild(wrap)});if(!document.getElementById('docV3Style')){const s=document.createElement('style');s.id='docV3Style';s.textContent='.doc-v3-actions{display:flex;gap:7px;flex-wrap:wrap;margin-top:8px}@media(max-width:600px){.doc-v3-actions{display:grid;grid-template-columns:1fr 1fr}.doc-v3-actions .button{width:100%}}';document.head.appendChild(s)}}
let raf=0;const scheduleEnhance=()=>{if(raf)return;raf=requestAnimationFrame(()=>{raf=0;enhanceOrders()})};
async function send(kind,id,defaultRecipient=''){const recipient=prompt('E-mailadres ontvanger:',defaultRecipient)??null;if(recipient===null)return;const message=prompt('Optionele begeleidende tekst:','')??null;if(message===null)return;const fd=new FormData();fd.set('kind',kind);fd.set('order_id',id);fd.set('recipient',recipient);fd.set('message',message);const d=await api('/api/documents/email',{method:'POST',body:fd});alert(`Document verzonden naar ${d.recipient}.`)}
document.addEventListener('submit',async e=>{if(e.target.id!=='documentV3Form')return;e.preventDefault();try{const fd=new FormData(e.target);const logo=await fileData(document.getElementById('docLogo').files[0]);if(logo)fd.set('logo_data',logo);await api('/api/documents/settings',{method:'POST',body:fd});alert('Documentinstellingen opgeslagen.');await loadSettings()}catch(err){alert(err.message)}});
document.addEventListener('click',async e=>{try{if(e.target.id==='removeDocLogo'){if(!confirm('Logo verwijderen?'))return;await api('/api/documents/logo/remove',{method:'POST',body:new FormData()});await loadSettings();return}const p=e.target.closest('[data-doc-preview]');if(p){window.open(`/api/documents/${p.dataset.docPreview==='invoice'?'invoice':'packing-slip'}.pdf?id=${encodeURIComponent(p.dataset.orderId)}`,'_blank');return}const m=e.target.closest('[data-doc-mail]');if(m){await send(m.dataset.docMail,m.dataset.orderId,m.dataset.recipient||'');return}if(e.target.closest('[data-view="settings"]'))setTimeout(loadSettings,120);if(e.target.closest('[data-view="orders"],[data-go="orders"]'))setTimeout(scheduleEnhance,120)}catch(err){alert(err.message)}});
window.addEventListener('load',()=>{setTimeout(loadSettings,250);setTimeout(scheduleEnhance,350);const root=document.getElementById('orders');if(root)new MutationObserver(scheduleEnhance).observe(root,{childList:true,subtree:true})});document.addEventListener('stockroom:refresh',()=>setTimeout(scheduleEnhance,150));
})();

