(()=>{
  const sections=[
    {id:'sales-invoices',label:'Verkoopfacturen',icon:'€',selectors:[':scope > .section-head',':scope > .finance-toolbar',':scope > #financeSummary',':scope > #financeList']},
    {id:'debtors',label:'Debiteuren',icon:'◷',selectors:[':scope > #debtorPanel']},
    {id:'purchase-invoices',label:'Inkoopfacturen',icon:'↓',selectors:[':scope > #purchaseInvoicePanel']},
    {id:'payment-batches',label:'Betaalvoorstellen',icon:'✓',selectors:[':scope > #paymentBatchPanel']},
    {id:'bank-reconciliation',label:'Bankmutaties',icon:'⇄',selectors:[':scope > #bankReconciliationPanel']}
  ];
  let current='sales-invoices',scheduled=false;
  const financeTrigger=()=>document.querySelector('.nav-item[data-view="finance"]');
  function install(){const menu=document.getElementById('tradeSidebarSubmenu'),source=financeTrigger();if(!menu||!source||document.getElementById('financeSplitNavigation'))return false;const wrap=document.createElement('div');wrap.id='financeSplitNavigation';wrap.className='finance-split-navigation';wrap.innerHTML=sections.map(item=>`<button class="nav-item ux-subnav-item" type="button" data-finance-subview="${item.id}"><span>${item.icon}</span>${item.label}</button>`).join('');source.insertAdjacentElement('beforebegin',wrap);source.classList.add('finance-split-source');syncAvailability();return true}
  function nodes(item){const finance=document.getElementById('finance');if(!finance)return[];return item.selectors.flatMap(selector=>[...finance.querySelectorAll(selector)])}
  function syncAvailability(){for(const item of sections){const button=document.querySelector(`[data-finance-subview="${item.id}"]`),exists=nodes(item).length>0;if(button)button.hidden=!exists}const wrap=document.getElementById('financeSplitNavigation');if(wrap)wrap.hidden=![...wrap.querySelectorAll('[data-finance-subview]')].some(button=>!button.hidden)}
  function apply(id,scroll=true){const selected=sections.find(item=>item.id===id);if(!selected)return;current=id;for(const item of sections)for(const node of nodes(item))node.classList.toggle('finance-subview-hidden',item.id!==id);document.querySelectorAll('[data-finance-subview]').forEach(button=>button.classList.toggle('active',button.dataset.financeSubview===id));const finance=document.getElementById('finance');if(finance)finance.dataset.financeSubview=id;const title=document.getElementById('pageTitle');if(title&&document.getElementById('finance')?.classList.contains('active-view'))title.textContent=selected.label;if(scroll)requestAnimationFrame(()=>{const target=nodes(selected)[0]||document.getElementById('finance');target?.scrollIntoView({behavior:'smooth',block:'start'})})}
  function open(id){if(!sections.some(item=>item.id===id))return;current=id;financeTrigger()?.click();setTimeout(()=>{apply(id);document.querySelector('.sidebar')?.classList.remove('open')},70)}
  function styles(){if(document.getElementById('financeSubviewStyles'))return;const style=document.createElement('style');style.id='financeSubviewStyles';style.textContent='.finance-split-source{display:none!important}.finance-split-navigation{display:grid;gap:2px}.finance-split-navigation .nav-item{width:100%;grid-template-columns:20px 1fr auto!important}.finance-subview-hidden{display:none!important}@media(max-width:900px){.finance-split-navigation .nav-item{min-height:42px!important;padding:9px 10px!important}}';document.head.appendChild(style)}
  document.addEventListener('click',event=>{const button=event.target.closest('[data-finance-subview]');if(button){event.preventDefault();event.stopPropagation();open(button.dataset.financeSubview);return}if(event.target.closest('[data-debtor-open]'))current='debtors';const source=event.target.closest('.nav-item[data-view="finance"]');if(source)setTimeout(()=>apply(current||'sales-invoices',false),100)},true);
  document.addEventListener('stockroom:refresh',event=>{if(event.detail?.view==='finance')setTimeout(()=>{syncAvailability();apply(current,false)},120)});
  new MutationObserver(records=>{if(scheduled)return;const relevant=records.some(record=>[...record.addedNodes].some(node=>node.nodeType===1&&((node.id==='tradeSidebarSubmenu')||node.id==='finance'||node.matches?.('#debtorPanel,#purchaseInvoicePanel,#paymentBatchPanel,#bankReconciliationPanel')||node.querySelector?.('#tradeSidebarSubmenu,#finance,#debtorPanel,#purchaseInvoicePanel,#paymentBatchPanel,#bankReconciliationPanel'))));if(!relevant)return;scheduled=true;requestAnimationFrame(()=>{scheduled=false;install();syncAvailability();apply(current,false)})}).observe(document.body,{childList:true,subtree:true});
  styles();install();
})();
