(()=>{
  const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  function installTrash(){
    const finance=document.getElementById('finance'),head=finance?.querySelector('.section-head');if(!head||document.getElementById('financeTrashBtn'))return;
    const button=document.createElement('button');button.id='financeTrashBtn';button.type='button';button.className='button ghost';button.textContent='Prullenbak';head.appendChild(button);
    const dialog=document.createElement('dialog');dialog.id='financeTrashDialog';dialog.innerHTML='<div class="invoice-trash"><div class="dialog-head"><div><p class="eyebrow">Herstelbaar verwijderd</p><h2>Factuurprullenbak</h2></div><button type="button" class="icon-button" data-close-trash aria-label="Sluiten">×</button></div><div id="financeTrashList">Laden…</div></div>';document.body.appendChild(dialog);
    const style=document.createElement('style');style.textContent='.invoice-trash{padding:24px}.invoice-trash #financeTrashList{display:grid;gap:9px;margin-top:18px}.invoice-trash-card{display:flex;align-items:center;justify-content:space-between;gap:12px;border:1px solid var(--line);border-radius:11px;padding:12px}.invoice-trash-card small{display:block;color:var(--muted);margin-top:4px}.invoice-trash-actions{display:flex;gap:7px}@media(max-width:580px){.invoice-trash-card{align-items:stretch;flex-direction:column}.invoice-trash-actions{display:grid}.invoice-trash-card .button{width:100%}}';document.head.appendChild(style)
  }
  function enhance(){document.querySelectorAll('#financeList .finance-card').forEach(card=>{const actions=card.querySelector('.finance-actions');if(!actions||actions.querySelector('[data-fin-delete]'))return;const source=actions.querySelector('[data-fin-pay],[data-fin-remind],[data-fin-credit]'),pdf=actions.querySelector('a[href*="invoice.pdf?id="]');const orderId=source?.dataset.finPay||source?.dataset.finRemind||source?.dataset.finCredit||new URL(pdf?.href||location.href).searchParams.get('id');if(!orderId)return;const number=card.querySelector('.finance-head strong')?.textContent?.trim()||'Deze factuur',button=document.createElement('button');button.type='button';button.className='button ghost finance-delete';button.dataset.finDelete=orderId;button.dataset.invoiceNumber=number;button.textContent='Verwijderen';actions.appendChild(button)})}
  async function showTrash(){installTrash();const dialog=document.getElementById('financeTrashDialog'),list=document.getElementById('financeTrashList');dialog.showModal();list.textContent='Laden…';try{const response=await fetch('/api/finance/trash',{cache:'no-store'}),data=await response.json();if(!response.ok)throw new Error(data.error||'Prullenbak laden mislukt.');list.innerHTML=data.invoices?.length?data.invoices.map(row=>`<article class="invoice-trash-card"><div><strong>${esc(row.invoice_number)}</strong><small>${esc(row.relation_name||'Geen relatie')} · order ${esc(row.order_number||'—')}</small><small>Verwijderd ${new Date(row.deleted_at).toLocaleString('nl-NL')} · ${Number(row.payments||0)} betaling(en) · ${Number(row.credits||0)} creditnota('s)</small></div><div class="invoice-trash-actions"><button type="button" class="button primary" data-fin-restore="${esc(row.order_id)}">Herstellen</button><button type="button" class="button ghost" data-fin-purge="${esc(row.order_id)}" data-invoice-number="${esc(row.invoice_number)}">Definitief verwijderen</button></div></article>`).join(''):'<p class="empty">De prullenbak is leeg.</p>'}catch(error){list.textContent=error.message}}
  async function remove(button){const number=button.dataset.invoiceNumber||'Deze factuur';if(!confirm(`${number} naar de prullenbak verplaatsen? De order, betalingen en creditnota's blijven behouden en de factuur kan later worden hersteld.`))return;button.disabled=true;try{const body=new FormData();body.set('order_id',button.dataset.finDelete);const response=await fetch('/api/finance/delete',{method:'POST',body}),data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||'Factuur verwijderen mislukt.');button.closest('.finance-card')?.remove();document.dispatchEvent(new CustomEvent('stockroom:refresh'));document.getElementById('refreshFinance')?.click()}catch(error){button.disabled=false;alert(error.message)}}
  async function restore(button){button.disabled=true;try{const body=new FormData();body.set('order_id',button.dataset.finRestore);const response=await fetch('/api/finance/restore',{method:'POST',body}),data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||'Factuur herstellen mislukt.');button.closest('.invoice-trash-card')?.remove();document.dispatchEvent(new CustomEvent('stockroom:refresh'));document.getElementById('refreshFinance')?.click()}catch(error){button.disabled=false;alert(error.message)}}
  async function purge(button){const number=button.dataset.invoiceNumber||'Deze factuur';if(!confirm(`${number} definitief verwijderen? Dit kan niet ongedaan worden gemaakt. Betalingen en creditnota's van deze factuur worden ook verwijderd; de verkooporder blijft behouden.`))return;button.disabled=true;try{const body=new FormData();body.set('order_id',button.dataset.finPurge);const response=await fetch('/api/finance/delete-permanently',{method:'POST',body}),data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||'Definitief verwijderen mislukt.');button.closest('.invoice-trash-card')?.remove();document.dispatchEvent(new CustomEvent('stockroom:refresh'))}catch(error){button.disabled=false;alert(error.message)}}
  document.addEventListener('click',event=>{const removeButton=event.target.closest('[data-fin-delete]');if(removeButton){event.preventDefault();remove(removeButton);return}const restoreButton=event.target.closest('[data-fin-restore]');if(restoreButton){restore(restoreButton);return}const purgeButton=event.target.closest('[data-fin-purge]');if(purgeButton){purge(purgeButton);return}if(event.target.closest('#financeTrashBtn')){showTrash();return}if(event.target.closest('[data-close-trash]')){document.getElementById('financeTrashDialog')?.close();return}if(event.target.closest('[data-view="finance"],#refreshFinance'))setTimeout(()=>{installTrash();enhance()},350)});
  const observer=new MutationObserver(enhance);window.addEventListener('load',()=>{const list=document.getElementById('financeList');if(list)observer.observe(list,{childList:true,subtree:true});setTimeout(()=>{installTrash();enhance()},500)});
})();
