(()=>{
  const definitions=[
    {id:'customers',label:'Klanten',icon:'♙',view:'relations',panel:'customerPanel'},
    {id:'suppliers',label:'Leveranciers',icon:'♟',view:'relations',panel:'supplierPanel'},
    {id:'sales-orders',label:'Verkooporders',icon:'↑',view:'orders',panel:'salesPanel'},
    {id:'purchase-orders',label:'Inkooporders',icon:'↓',view:'orders',panel:'purchasePanel'}
  ];
  let current='';let scheduled=false;
  function source(view){return document.querySelector(`.nav-item[data-view="${view}"]`)}
  function install(){const menu=document.getElementById('tradeSidebarSubmenu');if(!menu||document.getElementById('crmSplitNavigation'))return false;const wrap=document.createElement('div');wrap.id='crmSplitNavigation';wrap.className='crm-split-navigation';wrap.innerHTML=definitions.map(item=>`<button class="nav-item ux-subnav-item" type="button" data-crm-subview="${item.id}"><span>${item.icon}</span>${item.label}</button>`).join('');const quote=menu.querySelector('[data-view="quotes"]');quote?menu.insertBefore(wrap,quote):menu.prepend(wrap);source('relations')?.classList.add('crm-split-source');source('orders')?.classList.add('crm-split-source');syncAvailability();return true}
  function syncAvailability(){for(const item of definitions){const button=document.querySelector(`[data-crm-subview="${item.id}"]`),panel=document.getElementById(item.panel);if(button)button.hidden=!!panel?.hidden}const wrap=document.getElementById('crmSplitNavigation');if(wrap)wrap.hidden=![...wrap.querySelectorAll('[data-crm-subview]')].some(button=>!button.hidden)}
  function apply(id,scroll=true){const item=definitions.find(entry=>entry.id===id);if(!item)return;current=id;for(const entry of definitions.filter(entry=>entry.view===item.view)){document.getElementById(entry.panel)?.classList.toggle('crm-subview-hidden',entry.id!==id)}document.querySelectorAll('[data-crm-subview]').forEach(button=>button.classList.toggle('active',button.dataset.crmSubview===id));const title=document.querySelector(`#${item.view} .section-head h2`);if(title)title.textContent=item.label;document.getElementById(item.view)?.setAttribute('data-crm-subview',id);if(scroll)requestAnimationFrame(()=>document.getElementById(item.panel)?.scrollIntoView({behavior:'smooth',block:'start'}))}
  function clear(view){current='';for(const item of definitions.filter(entry=>entry.view===view))document.getElementById(item.panel)?.classList.remove('crm-subview-hidden');document.querySelectorAll('[data-crm-subview]').forEach(button=>button.classList.remove('active'));const title=document.querySelector(`#${view} .section-head h2`);if(title)title.textContent=view==='relations'?'Leveranciers & klanten':'Inkoop- & verkooporders';document.getElementById(view)?.removeAttribute('data-crm-subview')}
  function open(id){const item=definitions.find(entry=>entry.id===id),trigger=item&&source(item.view);if(!item||!trigger)return;trigger.click();setTimeout(()=>{apply(id);document.querySelector('.sidebar')?.classList.remove('open')},40)}
  function styles(){if(document.getElementById('crmSubviewStyles'))return;const style=document.createElement('style');style.id='crmSubviewStyles';style.textContent='.crm-split-source{display:none!important}.crm-split-navigation{display:grid;gap:2px}.crm-split-navigation .nav-item{width:100%;grid-template-columns:20px 1fr auto!important}.crm-subview-hidden{display:none!important}@media(max-width:900px){.crm-split-navigation .nav-item{min-height:42px!important;padding:9px 10px!important}}';document.head.appendChild(style)}
  document.addEventListener('click',event=>{const button=event.target.closest('[data-crm-subview]');if(button){event.preventDefault();event.stopPropagation();open(button.dataset.crmSubview);return}const nav=event.target.closest('.nav-item[data-view]');if(nav&&['relations','orders'].includes(nav.dataset.view)&&!event.isTrusted)setTimeout(()=>{if(!current)clear(nav.dataset.view)},0)},true);
  document.addEventListener('stockroom:refresh',event=>{if(['relations','orders'].includes(event.detail?.view))setTimeout(()=>{syncAvailability();if(current)apply(current,false)},80)});
  new MutationObserver(records=>{if(scheduled)return;const relevant=records.some(record=>record.type==='attributes'&&['supplierPanel','customerPanel','purchasePanel','salesPanel'].includes(record.target.id)||[...record.addedNodes].some(node=>node.nodeType===1&&((node.id==='tradeSidebarSubmenu')||node.querySelector?.('#tradeSidebarSubmenu,#supplierPanel,#customerPanel,#purchasePanel,#salesPanel'))));if(!relevant)return;scheduled=true;requestAnimationFrame(()=>{scheduled=false;install();syncAvailability();if(current)apply(current,false)})}).observe(document.body,{childList:true,subtree:true,attributes:true,attributeFilter:['hidden']});
  styles();install();
})();
