(()=>{
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const money=v=>Number(v||0).toLocaleString('nl-NL',{style:'currency',currency:'EUR'});
  const api=async(url,options={})=>{const response=await fetch(url,{credentials:'same-origin',...options}),data=await response.json();if(!response.ok)throw new Error(data.error||'Actie mislukt.');return data};
  let data={settings:{},candidates:[],batches:[]},role='member',suppliers=[];
  function install(){const host=document.getElementById('finance');if(host&&!document.getElementById('paymentBatchPanel'))host.insertAdjacentHTML('beforeend',`<article id="paymentBatchPanel" class="card"><div class="section-heading"><div><p class="eyebrow">Betalen</p><h2>Betaalvoorstellen en SEPA</h2><p>Alleen gecontroleerde facturen worden opgenomen. Verwerking boekt betalingen definitief.</p></div></div><div id="paymentBatchSettings"></div><form id="paymentProposalForm"><div class="section-heading"><h3>Beschikbare facturen</h3><label>Uitvoerdatum <input name="execution_date" type="date" required></label></div><div id="paymentCandidates"></div><button class="button" type="submit">Betaalvoorstel maken</button></form><div id="paymentBatchList"></div></article>`);ensureSupplierFields()}
  function ensureSupplierFields(){const form=document.getElementById('supplierForm');if(!form||form.elements.iban)return;const planning=form.querySelector('[name=minimum_order_amount]')?.closest('label');planning?.insertAdjacentHTML('beforebegin','<input name="iban" placeholder="IBAN voor betalingen"><input name="bic" placeholder="BIC (optioneel)">')}
  function render(){const settings=document.getElementById('paymentBatchSettings'),candidates=document.getElementById('paymentCandidates'),list=document.getElementById('paymentBatchList');if(!settings||!candidates||!list)return;settings.innerHTML=['owner','admin'].includes(role)?`<details ${data.settings.iban?'':'open'}><summary>Bankrekening organisatie</summary><form id="paymentSettingsForm" class="form-grid"><label>Rekeningnaam<input name="account_name" value="${esc(data.settings.account_name)}" required></label><label>IBAN<input name="iban" value="${esc(data.settings.iban)}" required></label><label>BIC<input name="bic" value="${esc(data.settings.bic)}"></label><button class="button" type="submit">Bankrekening opslaan</button></form></details>`:'';candidates.innerHTML=data.candidates.length?data.candidates.map(row=>`<label class="list-card"><input type="checkbox" name="invoice_id" value="${row.id}" ${row.bankReady?'':'disabled'}><span><strong>${esc(row.invoice_number)} · ${esc(row.supplier_name)}</strong><small>Vervalt ${new Date(row.due_date).toLocaleDateString('nl-NL')} · ${money(row.amount)}${row.bankReady?'':' · eerst geldig IBAN bij leverancier invullen'}</small></span></label>`).join(''):'<p>Geen goedgekeurde facturen beschikbaar voor een nieuwe betaalbatch.</p>';list.innerHTML=`<h3>Betaalbatches</h3>`+(data.batches.length?data.batches.map(batch=>`<div class="list-card"><div><strong>${esc(batch.batch_number)}</strong><small>${batch.item_count} betaling(en) · ${money(batch.total)} · uitvoer ${new Date(batch.execution_date).toLocaleDateString('nl-NL')}</small><span class="status-badge ${batch.status==='processed'?'success':batch.status==='cancelled'?'danger':'warning'}">${esc({draft:'concept',approved:'goedgekeurd',exported:'SEPA geëxporteerd',processed:'verwerkt',cancelled:'geannuleerd'}[batch.status]||batch.status)}</span>${batch.items.map(item=>`<small>${esc(item.creditor_name)} · ${esc(item.reference)} · ${money(item.amount)}</small>`).join('')}</div><div class="button-row">${batch.status==='draft'?`<button class="button" data-batch-action="approve" data-id="${batch.id}">Goedkeuren</button><button class="button ghost" data-batch-action="cancel" data-id="${batch.id}">Annuleren</button>`:''}${['approved','exported'].includes(batch.status)?`<a class="button" href="/api/payment-batches/sepa?id=${batch.id}">SEPA downloaden</a>`:''}${batch.status==='exported'?`<button class="button" data-batch-action="process" data-id="${batch.id}">Als verwerkt boeken</button>`:''}</div></div>`).join(''):'<p>Nog geen betaalbatches.</p>')}
  async function load(){install();ensureSupplierFields();const [me,result,supplierData]=await Promise.all([api('/api/me'),api('/api/payment-batches'),api('/api/suppliers')]);role=me.stockroom?.role||'member';data=result;suppliers=supplierData.items||[];const date=document.querySelector('#paymentProposalForm [name=execution_date]');if(date&&!date.value)date.value=new Date().toISOString().slice(0,10);render()}
  document.addEventListener('submit',async event=>{try{if(event.target.id==='paymentSettingsForm'){event.preventDefault();await api('/api/payment-settings',{method:'POST',body:new FormData(event.target)});await load();return}if(event.target.id==='paymentProposalForm'){event.preventDefault();const body=new FormData(event.target),ids=[...event.target.querySelectorAll('[name=invoice_id]:checked')].map(input=>input.value);body.set('invoice_ids',JSON.stringify(ids));await api('/api/payment-batches',{method:'POST',body});await load()}}catch(error){alert(error.message)}});
  document.addEventListener('click',async event=>{const edit=event.target.closest('[data-edit-relation="supplier"]');if(edit)setTimeout(()=>{ensureSupplierFields();const supplier=suppliers.find(row=>row.id===edit.dataset.id),form=document.getElementById('supplierForm');if(supplier&&form){form.elements.iban.value=supplier.iban||'';form.elements.bic.value=supplier.bic||''}},0);const button=event.target.closest('[data-batch-action]');if(!button)return;try{if(button.dataset.batchAction==='process'&&!confirm('Bevestig dat de bank deze batch heeft uitgevoerd. De facturen worden daarna als betaald geboekt.'))return;const body=new FormData();body.set('batch_id',button.dataset.id);await api(`/api/payment-batches/${button.dataset.batchAction}`,{method:'POST',body});await load();document.dispatchEvent(new CustomEvent('stockroom:refresh',{detail:{view:'finance'}}))}catch(error){alert(error.message)}});
  document.addEventListener('stockroom:refresh',event=>{if(event.detail?.view==='finance')load()});new MutationObserver(()=>ensureSupplierFields()).observe(document.body,{childList:true,subtree:true});install();load().catch(()=>{});
})();
