(()=>{
const labels={cash:'Cash',bank:'Online / bank'};
let editingPaymentMethod=null;
function installField(){const form=document.getElementById('transactionForm');if(!form||document.getElementById('paymentMethodLabel'))return;const status=document.getElementById('statusLabel');const label=document.createElement('label');label.id='paymentMethodLabel';label.className='transaction-fields';label.innerHTML='<span>Betaalmethode</span><select id="paymentMethod"><option value="bank">Online / bank</option><option value="cash">Cash</option></select>';status?.insertAdjacentElement('afterend',label)}
function syncVisibility(){const type=document.getElementById('transactionType')?.value;const label=document.getElementById('paymentMethodLabel');if(label)label.hidden=type==='item'}
function setMethodForEdit(id){installField();const tx=typeof state!=='undefined'?state.transactions.find(t=>t.id===id):null;editingPaymentMethod=tx?.paymentMethod||null;const apply=()=>{const select=document.getElementById('paymentMethod');if(select&&editingPaymentMethod&&['cash','bank'].includes(editingPaymentMethod))select.value=editingPaymentMethod;syncVisibility()};apply();requestAnimationFrame(apply);setTimeout(apply,30);setTimeout(apply,100)}
function resetMethodForNew(){editingPaymentMethod=null;installField();const select=document.getElementById('paymentMethod');if(select)select.value='bank';syncVisibility()}
function renderMethods(){document.querySelectorAll('#incomingCards .transaction-card,#outgoingCards .transaction-card').forEach(card=>{const edit=card.querySelector('[data-edit-transaction]');if(!edit||card.querySelector('.payment-method-line'))return;const tx=state.transactions.find(t=>t.id===edit.dataset.editTransaction);if(!tx)return;const paid=tx.type==='incoming'?!!tx.paid:!!tx.done;if(!paid)return;const controls=card.querySelector('.transaction-controls');if(!controls)return;const line=document.createElement('div');line.className='payment-method-line';line.innerHTML=`<small>Betaalmethode</small><strong>${labels[tx.paymentMethod]||'Niet opgegeven'}</strong>`;controls.insertAdjacentElement('beforebegin',line)})}
function rerender(){if(typeof render==='function')render();requestAnimationFrame(renderMethods)}
window.addEventListener('load',()=>{installField();syncVisibility();setTimeout(renderMethods,300)});
document.addEventListener('click',e=>{const typeBtn=e.target.closest('.type-switch [data-type]');if(typeBtn)setTimeout(syncVisibility,0);const edit=e.target.closest('[data-edit-transaction]');if(edit){const id=edit.dataset.editTransaction;setTimeout(()=>setMethodForEdit(id),0)}if(e.target.closest('[data-add],#quickAddBtn'))setTimeout(resetMethodForNew,0);if(e.target.closest('[data-toggle],[data-toggle-paid]'))setTimeout(renderMethods,80)});
document.addEventListener('submit',e=>{if(e.target.id!=='transactionForm')return;const type=document.getElementById('transactionType')?.value;if(type==='item')return;const editId=typeof editingTransactionId!=='undefined'?editingTransactionId:null;const existing=editId&&typeof state!=='undefined'?state.transactions.find(t=>t.id===editId):null;const selected=document.getElementById('paymentMethod')?.value;const method=(selected&&['cash','bank'].includes(selected))?selected:(existing?.paymentMethod||editingPaymentMethod||'bank');setTimeout(()=>{let tx=editId?state.transactions.find(t=>t.id===editId):null;if(!tx){tx=[...state.transactions].filter(t=>t.type===type).sort((a,b)=>new Date(b.date)-new Date(a.date))[0]}if(!tx)return;tx.paymentMethod=method;if(typeof save==='function')save();editingPaymentMethod=null;rerender()},0)},true);
const observer=new MutationObserver(records=>{for(const r of records){for(const n of r.addedNodes){if(n.nodeType===1&&(n.matches?.('.transaction-card')||n.querySelector?.('.transaction-card'))){requestAnimationFrame(renderMethods);return}}}});['incomingCards','outgoingCards'].forEach(id=>{const el=document.getElementById(id);if(el)observer.observe(el,{childList:true,subtree:true})});
})();
