(()=>{
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const money=v=>Number(v||0).toLocaleString('nl-NL',{style:'currency',currency:'EUR'}),now=new Date();
  const api=async(url,options={})=>{const response=await fetch(url,{credentials:'same-origin',...options}),data=await response.json();if(!response.ok)throw new Error(data.error||'Actie mislukt.');return data};
  let report=null,role='member';
  function install(){const analytics=document.getElementById('analyticsContent'),host=analytics||document.getElementById('finance'),existing=document.getElementById('profitReportPanel');if(!host)return false;if(existing){if(analytics&&existing.parentElement!==analytics)analytics.appendChild(existing);return true}host.insertAdjacentHTML('beforeend',`<article id="profitReportPanel" class="card"><div class="section-heading"><div><p class="eyebrow">Resultaat</p><h2>Winst, verlies en marges</h2><p>Historische omzet, handmatige transacties, kostprijs, bedrijfskosten en vergelijking met de vorige periode.</p></div><form id="profitPeriodForm" class="button-row"><input name="year" type="number" min="2000" max="2100" value="${now.getFullYear()}" aria-label="Jaar"><select name="mode"><option value="month">Maand</option><option value="quarter">Kwartaal</option><option value="year">Jaar</option></select><select name="value" aria-label="Periode"></select><button class="button" type="submit">Tonen</button></form></div><div id="profitSummary"></div><div id="profitAlerts"></div><div id="profitBreakdowns"></div><div id="expenseManager"></div></article>`);periodOptions();return true}
  function periodOptions(){const form=document.getElementById('profitPeriodForm');if(!form)return;const mode=form.elements.mode.value,select=form.elements.value,current=select.value;select.innerHTML=mode==='month'?Array.from({length:12},(_,i)=>`<option value="${i+1}">${new Date(2020,i,1).toLocaleDateString('nl-NL',{month:'long'})}</option>`).join(''):mode==='quarter'?[1,2,3,4].map(i=>`<option value="${i}">Q${i}</option>`).join(''):`<option value="${form.elements.year.value}">${form.elements.year.value}</option>`;select.value=current||String(mode==='month'?now.getMonth()+1:mode==='quarter'?Math.floor(now.getMonth()/3)+1:form.elements.year.value)}
  function breakdown(title,rows){return `<details><summary>${title}</summary><div class="table-wrap"><table><thead><tr><th>Naam</th><th>Omzet</th><th>Kostprijs</th><th>Marge</th><th>%</th></tr></thead><tbody>${rows.map(row=>`<tr><td>${esc(row.name)}</td><td>${money(row.revenue)}</td><td>${money(row.cost)}</td><td>${money(row.margin)}</td><td>${row.marginPercent}%</td></tr>`).join('')||'<tr><td colspan="5">Geen gegevens.</td></tr>'}</tbody></table></div></details>`}
  function render(){const s=report.summary,summary=document.getElementById('profitSummary'),alerts=document.getElementById('profitAlerts'),breakdowns=document.getElementById('profitBreakdowns'),expenses=document.getElementById('expenseManager');summary.innerHTML=`<div class="metric-grid"><div class="metric"><span>Omzet</span><strong>${money(s.revenue)}</strong><small>${report.change.revenue>=0?'+':''}${money(report.change.revenue)} t.o.v. vorige periode</small></div><div class="metric"><span>Inkoopwaarde omzet</span><strong>${money(s.costOfGoods)}</strong></div><div class="metric"><span>Brutowinst · ${s.grossMarginPercent}%</span><strong>${money(s.grossProfit)}</strong></div><div class="metric"><span>Bedrijfskosten</span><strong>${money(s.operatingExpenses)}</strong></div><div class="metric"><span>Nettoresultaat</span><strong>${money(s.netProfit)}</strong><small>${report.change.netProfit>=0?'+':''}${money(report.change.netProfit)} t.o.v. vorige periode</small></div></div><a class="button" href="/api/profit-report/export?year=${report.period.year}&mode=${report.period.mode}&value=${report.period.value}">Resultaatrapport downloaden</a>`;alerts.innerHTML=report.alerts.length?`<div class="notice warning"><strong>Aandachtspunten</strong>${report.alerts.map(x=>`<p>${esc(x)}</p>`).join('')}</div>`:'<div class="notice success">Geen margewaarschuwingen in deze periode.</div>';breakdowns.innerHTML=breakdown('Marge per artikel',report.byItem)+breakdown('Marge per klant',report.byCustomer)+breakdown('Marge per leverancier',report.bySupplier);expenses.innerHTML=`<details><summary>Bedrijfskosten (${report.expenses.length})</summary>${report.expenses.map(row=>`<div class="list-card"><span>${new Date(row.expense_date).toLocaleDateString('nl-NL')} · ${esc(row.category)} · ${money(row.net_amount)} · ${esc(row.description)}</span>${row.category!=='Bankkosten'&&['owner','admin'].includes(role)?`<button class="button ghost" data-delete-expense="${row.id}">Verwijderen</button>`:''}</div>`).join('')||'<p>Geen bedrijfskosten in deze periode.</p>'}${['owner','admin'].includes(role)?`<form id="expenseForm" class="form-grid"><label>Datum<input name="expense_date" type="date" value="${new Date().toISOString().slice(0,10)}" required></label><label>Categorie<input name="category" placeholder="Bijv. huisvesting" required></label><label>Leverancier<input name="supplier_name"></label><label>Omschrijving<input name="description" required></label><label>Bedrag excl. btw<input name="net_amount" type="number" min="0" step="0.01" required></label><label>Btw<input name="vat_amount" type="number" step="0.01" value="0"></label><button class="button" type="submit">Kosten boeken</button></form>`:''}</details>`}
  async function load(){install();const form=document.getElementById('profitPeriodForm'),query=new URLSearchParams(new FormData(form)),[me,data]=await Promise.all([api('/api/me'),api('/api/profit-report?'+query)]);role=me.stockroom?.role||'member';report=data;render();const costLabel=document.querySelector('#profitSummary .metric:nth-child(2) span');if(costLabel)costLabel.textContent='Inkoopwaarde / handmatige inkoop'}
  let loadPromise=null,loadQueued=false,retryCount=0,retryTimer=null;
  function reliableLoad(){if(loadPromise){loadQueued=true;return loadPromise}loadPromise=load().then(()=>{retryCount=0}).catch(()=>{if(retryCount<3){retryCount++;clearTimeout(retryTimer);retryTimer=setTimeout(reliableLoad,retryCount*400)}}).finally(()=>{loadPromise=null;if(loadQueued){loadQueued=false;reliableLoad()}});return loadPromise}
  document.addEventListener('change',event=>{if(event.target.closest('#profitPeriodForm')&&event.target.name==='mode')periodOptions()});
  document.addEventListener('submit',async event=>{try{if(event.target.id==='profitPeriodForm'){event.preventDefault();periodOptions();await load();return}if(event.target.id==='expenseForm'){event.preventDefault();await api('/api/operating-expenses',{method:'POST',body:new FormData(event.target)});await load()}}catch(error){alert(error.message)}});
  document.addEventListener('click',async event=>{const button=event.target.closest('[data-delete-expense]');if(!button||!confirm('Deze kostenpost verwijderen?'))return;try{const body=new FormData();body.set('expense_id',button.dataset.deleteExpense);await api('/api/operating-expenses/delete',{method:'POST',body});await load()}catch(error){alert(error.message)}});
  document.addEventListener('stockroom:refresh',event=>{if(event.detail?.view==='analytics')reliableLoad()});install();reliableLoad();
  document.addEventListener('stockroom:analytics-ready',reliableLoad);
  new MutationObserver(()=>{if(document.getElementById('analyticsContent')&&!document.getElementById('profitReportPanel'))reliableLoad()}).observe(document.body,{childList:true,subtree:true});
})();
