(() => {
  const esc=value=>String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  let orders=[],active=null;
  async function api(url,options={}){const response=await fetch(url,{cache:'no-store',...options}),data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||'Actie mislukt.');return data}
  function install(){if(document.getElementById('receiptDialog'))return;const dialog=document.createElement('dialog');dialog.id='receiptDialog';dialog.innerHTML='<form id="receiptForm"><div class="dialog-head"><div><p class="eyebrow">Inkooporder</p><h2 id="receiptTitle">Ontvangst registreren</h2></div><button class="icon-button" type="button" data-close-receipt>×</button></div><p class="receipt-help">Boek alleen wat daadwerkelijk is binnengekomen. De resterende aantallen blijven openstaan.</p><div id="receiptLines"></div><div class="field-grid"><label>Pakbon / referentie<input name="reference" placeholder="Bijv. PB-1024"></label><label>Ontvangstdatum<input value="Vandaag" disabled></label></div><label>Notitie<input name="note" placeholder="Bijv. nalevering verwacht"></label><div class="dialog-actions"><button class="button ghost" type="button" data-close-receipt>Annuleren</button><button class="button primary" type="submit">Ontvangst boeken</button></div><div id="receiptHistory"></div></form>';document.body.appendChild(dialog);const style=document.createElement('style');style.textContent='.receipt-button{margin:8px 6px 0 0}.receipt-help{color:var(--muted);font-size:11px}.receipt-line{display:grid;grid-template-columns:minmax(150px,1fr) 100px 120px;gap:9px;align-items:center;padding:9px 0;border-top:1px solid var(--line)}.receipt-line small{display:block;color:var(--muted)}.receipt-history{margin-top:18px;border-top:1px solid var(--line);padding-top:12px}.receipt-event{display:flex;justify-content:space-between;gap:10px;padding:9px 0;border-bottom:1px solid var(--line)}.receipt-event small{display:block;color:var(--muted)}@media(max-width:580px){.receipt-line{grid-template-columns:1fr 100px}.receipt-line>span{grid-column:1/-1}.receipt-event{display:block}.receipt-event button{width:100%;margin-top:8px}}';document.head.appendChild(style)}
  async function load(){orders=(await api('/api/orders?type=purchase')).orders||[];enhance()}
  function enhance(){document.querySelectorAll('[data-order-card-type="purchase"]').forEach(card=>{if(card.querySelector('.receipt-button'))return;const order=orders.find(row=>row.id===card.dataset.orderCardId);if(!order)return;const button=document.createElement('button');button.type='button';button.className='button ghost receipt-button';button.dataset.receiptOrder=order.id;button.textContent=order.status==='received'?'Ontvangsten bekijken':'Ontvangst boeken';card.appendChild(button)})}
  async function open(orderId){active=orders.find(row=>row.id===orderId);if(!active){await load();active=orders.find(row=>row.id===orderId)}if(!active)return;const receipts=(await api('/api/orders/receipts?order_id='+encodeURIComponent(orderId))).receipts||[];document.getElementById('receiptTitle').textContent=active.order_number||active.reference||'Ontvangst registreren';document.getElementById('receiptLines').innerHTML=active.lines.map(line=>{const remaining=Math.max(0,Number(line.quantity)-Number(line.fulfilled_quantity||0));return `<label class="receipt-line"><span><strong>${esc(line.item_name)}</strong><small>${Number(line.fulfilled_quantity||0).toLocaleString('nl-NL')} ontvangen van ${Number(line.quantity).toLocaleString('nl-NL')}</small></span><span>${remaining.toLocaleString('nl-NL')} open</span><input data-receipt-line="${esc(line.id)}" type="number" min="0" max="${remaining}" step="0.001" value="0" ${remaining<=0?'disabled':''}></label>`}).join('');document.getElementById('receiptHistory').innerHTML=`<div class="receipt-history"><strong>Ontvangsthistorie</strong>${receipts.length?receipts.map(receipt=>`<div class="receipt-event"><div><strong>${esc(receipt.reference||'Ontvangst')}</strong><small>${new Date(receipt.received_at).toLocaleString('nl-NL')} · ${esc(receipt.received_by_name||'Onbekend')}</small><small>${receipt.lines.map(line=>`${Number(line.quantity).toLocaleString('nl-NL')}× ${esc(line.item_name)}`).join(' · ')}</small>${receipt.reversed_at?'<small>Teruggedraaid</small>':''}</div>${receipt.reversed_at?'':`<button class="button ghost" type="button" data-reverse-receipt="${receipt.id}">Terugdraaien</button>`}</div>`).join(''):'<p class="receipt-help">Nog geen ontvangsten geregistreerd.</p>'}</div>`;document.getElementById('receiptForm').elements.reference.value='';document.getElementById('receiptForm').elements.note.value='';document.getElementById('receiptDialog').showModal()}
  async function refresh(){await load();if(active)await open(active.id);document.dispatchEvent(new CustomEvent('orders:refresh'))}
  document.addEventListener('click',async event=>{try{const button=event.target.closest('[data-receipt-order]');if(button){await open(button.dataset.receiptOrder);return}if(event.target.closest('[data-close-receipt]')){active=null;document.getElementById('receiptDialog').close();return}const reverse=event.target.closest('[data-reverse-receipt]');if(reverse&&confirm('Deze ontvangst terugdraaien? De ontvangen voorraad wordt weer afgeboekt.')){const body=new FormData();body.set('receipt_id',reverse.dataset.reverseReceipt);await api('/api/orders/receipt/reverse',{method:'POST',body});await refresh()}}catch(error){alert(error.message)}});
  document.addEventListener('submit',async event=>{if(event.target.id!=='receiptForm')return;event.preventDefault();try{const lines=[...document.querySelectorAll('[data-receipt-line]')].map(input=>({line_id:input.dataset.receiptLine,quantity:Number(input.value)})).filter(line=>line.quantity>0),body=new FormData(event.target);body.set('order_id',active.id);body.set('lines_json',JSON.stringify(lines));await api('/api/orders/receive',{method:'POST',body});await refresh()}catch(error){alert(error.message)}});
  document.addEventListener('stockroom:refresh',event=>{if(event.detail?.view==='orders')load()});document.addEventListener('orders:refresh',()=>setTimeout(load,50));
  install();load();new MutationObserver(enhance).observe(document.getElementById('purchaseOrders')||document.body,{childList:true,subtree:true});
})();

