(() => {
  const esc=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
  const euro=new Intl.NumberFormat('nl-NL',{style:'currency',currency:'EUR'});let loading=false;
  function install(){
    const host=document.getElementById('purchaseAdvicePanel')||document.querySelector('.forecast-panel');if(!host||document.getElementById('purchaseIntelligence'))return;
    host.insertAdjacentHTML('afterend','<article class="panel purchase-intelligence" id="purchaseIntelligence"><div class="panel-head"><div><p class="eyebrow">Inkoopdata</p><h3>Leveranciersscore & prijshistorie</h3></div><button class="button ghost" type="button" id="refreshPurchaseIntelligence">Vernieuwen</button></div><div id="purchaseIntelligenceBody" class="empty">Inkoopgegevens laden…</div></article>');
    const style=document.createElement('style');style.textContent='.purchase-intelligence{margin-top:14px}.supplier-score-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:9px;margin:12px 0}.supplier-score{border:1px solid var(--line);border-radius:11px;padding:11px}.supplier-score strong,.supplier-score small{display:block}.supplier-score small{color:var(--muted);margin-top:3px}.score-pill{float:right;border-radius:99px;padding:4px 8px;background:var(--green-2);color:var(--green)}.purchase-recommendations{display:grid;gap:7px}.purchase-recommendation{display:grid;grid-template-columns:minmax(130px,1fr) minmax(130px,1fr) 100px 90px;gap:8px;align-items:center;padding:9px;border-top:1px solid var(--line)}.purchase-recommendation small{display:block;color:var(--muted)}@media(max-width:760px){.supplier-score-grid{grid-template-columns:1fr}.purchase-recommendation{grid-template-columns:1fr 1fr}.purchase-recommendation>:first-child{grid-column:1/-1}}';document.head.appendChild(style);
  }
  const confidence=value=>({high:'sterke onderbouwing',medium:'redelijke onderbouwing',low:'beperkte historie'}[value]||value);
  async function refresh(){
    install();const body=document.getElementById('purchaseIntelligenceBody');if(!body||loading)return;loading=true;body.textContent='Inkoopgegevens laden…';
    try{const response=await fetch('/api/purchase-intelligence',{cache:'no-store'}),data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||'Inkoopanalyse kon niet worden geladen.');body.className='';body.innerHTML=`<div class="supplier-score-grid">${data.suppliers.length?data.suppliers.map(row=>`<div class="supplier-score"><span class="score-pill">${row.score}/100</span><strong>${esc(row.name)}</strong><small>${row.orders} order${row.orders===1?'':'s'} · ${confidence(row.confidence)}</small><small>Levertijd ${row.avgLeadDays===null?'nog onbekend':`${row.avgLeadDays} dagen`} · retour ${row.returnRate}%</small></div>`).join(''):'<div class="empty">Nog onvoldoende inkoophistorie.</div>'}</div><h4>Beste leverancier per artikel</h4><div class="purchase-recommendations">${data.recommendations.map(row=>{const best=row.recommended;return `<div class="purchase-recommendation"><div><strong>${esc(row.itemName)}</strong><small>${esc(row.sku||'Geen SKU')}</small></div><div><strong>${esc(best?.supplierName||'Geen advies')}</strong><small>${best?.samples||0} prijsmeting${best?.samples===1?'':'en'}</small></div><span>${best?euro.format(best.latestPrice):'—'}</span><span>${best?.priceChange===null||best?.priceChange===undefined?'geen trend':`${best.priceChange>0?'+':''}${best.priceChange}%`}</span></div>`}).join('')}</div><details><summary>Recente inkoopprijzen (${data.priceHistory.length})</summary><div class="purchase-recommendations">${data.priceHistory.slice(0,30).map(row=>`<div class="purchase-recommendation"><strong>${esc(row.itemName)}</strong><span>${esc(row.supplierName)}</span><span>${euro.format(row.price)}</span><span>${new Date(row.date).toLocaleDateString('nl-NL')}</span></div>`).join('')}</div></details>`}catch(error){body.className='empty';body.textContent=error.message}finally{loading=false}
  }
  document.addEventListener('click',event=>{if(event.target.closest('#refreshPurchaseIntelligence'))refresh()});document.addEventListener('stockroom:refresh',event=>{if(event.detail?.view==='inventory')refresh()});
  const observer=new MutationObserver(()=>{install();if(document.getElementById('purchaseIntelligence')&&!document.getElementById('purchaseIntelligence').dataset.loaded){document.getElementById('purchaseIntelligence').dataset.loaded='1';refresh()}});observer.observe(document.body,{childList:true,subtree:true});install();refresh();
})();
