(() => {
  let me=null,orders=[],policy=null;
  async function api(url,options={}){const response=await fetch(url,{cache:'no-store',...options}),data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||'Actie mislukt.');return data}
  const canApprove=()=>['owner','admin'].includes(me?.stockroom?.role);
  function installPolicy(){const host=document.getElementById('purchaseIntelligence');if(!host||document.getElementById('purchasePolicy'))return;host.insertAdjacentHTML('beforeend','<form id="purchasePolicy" class="purchase-policy"><strong>Goedkeuring & maandbudget</strong><label>Goedkeuring vanaf (€)<input name="approval_threshold" type="number" min="0" step="0.01"></label><label>Maandbudget (€; 0 is onbeperkt)<input name="monthly_budget" type="number" min="0" step="0.01"></label><label><input name="price_warning_requires_approval" type="checkbox" value="1"> Prijswaarschuwing altijd goedkeuren</label><button class="button primary">Beleid opslaan</button><span id="purchasePolicyStatus" role="status"></span></form>');const style=document.createElement('style');style.textContent='.purchase-policy{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px;margin-top:16px;padding-top:14px;border-top:1px solid var(--line)}.purchase-policy>strong,.purchase-policy>span{grid-column:1/-1}.purchase-policy input{padding:8px;border:1px solid var(--line);border-radius:8px}.approval-actions{display:flex;gap:6px;flex-wrap:wrap;margin-top:8px}.approval-note{display:block;color:#9a6700;margin-top:6px}@media(max-width:650px){.purchase-policy{grid-template-columns:1fr}}';document.head.appendChild(style)}
  function fillPolicy(){installPolicy();const form=document.getElementById('purchasePolicy');if(!form||!policy)return;form.hidden=!canApprove();form.elements.approval_threshold.value=Number(policy.approval_threshold||0).toFixed(2);form.elements.monthly_budget.value=Number(policy.monthly_budget||0).toFixed(2);form.elements.price_warning_requires_approval.checked=Boolean(policy.price_warning_requires_approval)}
  function enhance(){document.querySelectorAll('.order-card[data-order-card-type="purchase"]').forEach(card=>{card.querySelector('.approval-actions')?.remove();card.querySelector('.approval-note')?.remove();const order=orders.find(row=>row.id===card.dataset.orderCardId);if(!order)return;if(order.status==='pending_approval'){card.insertAdjacentHTML('beforeend',`<small class="approval-note">Wacht op goedkeuring · ${order.approval_reason||'controle vereist'}</small>${canApprove()?`<div class="approval-actions"><button type="button" class="button primary" data-approve-order="${order.id}">Goedkeuren</button><button type="button" class="button ghost" data-reject-order="${order.id}">Afwijzen</button></div>`:''}`)}else if(['approved','rejected'].includes(order.approval_status)){card.insertAdjacentHTML('beforeend',`<small class="approval-note">${order.approval_status==='approved'?'Goedgekeurd':'Afgewezen'}${order.approved_by_name?` door ${order.approved_by_name}`:''}${order.approval_reason?` · ${order.approval_reason}`:''}</small>`)}})}
  async function refresh(){try{[me,policy]=await Promise.all([api('/api/me'),api('/api/purchase-policy')]);orders=(await api('/api/orders?type=purchase')).orders||[];fillPolicy();enhance()}catch(error){console.warn(error)}}
  document.addEventListener('submit',async event=>{if(event.target.id!=='purchasePolicy')return;event.preventDefault();const status=document.getElementById('purchasePolicyStatus');try{policy=await api('/api/purchase-policy',{method:'POST',body:new FormData(event.target)});status.textContent='Inkoopbeleid opgeslagen.';fillPolicy()}catch(error){status.textContent=error.message}});
  document.addEventListener('click',async event=>{const approve=event.target.closest('[data-approve-order]'),reject=event.target.closest('[data-reject-order]');if(!approve&&!reject)return;const reason=reject?prompt('Reden voor afwijzing:',''):prompt('Notitie bij goedkeuring (optioneel):','');if(reason===null||reject&&!reason.trim())return;const body=new FormData();body.set('order_id',(approve||reject).dataset[approve?'approveOrder':'rejectOrder']);body.set('reason',reason);try{await api(approve?'/api/orders/approve':'/api/orders/reject',{method:'POST',body});document.dispatchEvent(new CustomEvent('orders:refresh'));document.dispatchEvent(new CustomEvent('stockroom:refresh',{detail:{view:'overview'}}));await refresh()}catch(error){alert(error.message)}});
  document.addEventListener('orders:refresh',()=>setTimeout(refresh,100));document.addEventListener('stockroom:refresh',event=>{if(['inventory','orders'].includes(event.detail?.view))refresh()});new MutationObserver(()=>{installPolicy();enhance()}).observe(document.body,{childList:true,subtree:true});refresh();
})();
