(() => {
  const esc=value=>String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  let orders=[],active=null,state={items:[]},scanCount=0;
  async function api(url,options={}){const response=await fetch(url,{cache:'no-store',...options}),data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||'Actie mislukt.');return data}
  function install(){if(document.getElementById('receiptDialog'))return;const dialog=document.createElement('dialog');dialog.id='receiptDialog';dialog.innerHTML='<form id="receiptForm"><div class="dialog-head"><div><p class="eyebrow">Inkooporder</p><h2 id="receiptTitle">Ontvangst registreren</h2></div><button class="icon-button" type="button" data-close-receipt>×</button></div><p class="receipt-help">Boek alleen wat daadwerkelijk is binnengekomen. De resterende aantallen blijven openstaan.</p><div class="receipt-scan"><button class="button primary" type="button" id="scanReceiptBtn">▣ Camera scannen</button><label>Handscanner / barcode<input id="receiptBarcodeInput" inputmode="numeric" autocomplete="off" placeholder="Scan en druk op Enter"></label><span id="receiptScanStatus" role="status">Nog niets gescand.</span></div><div id="receiptLines"></div><div class="field-grid"><label>Pakbon / referentie<input name="reference" placeholder="Bijv. PB-1024"></label><label>Ontvangstdatum<input value="Vandaag" disabled></label></div><label>Notitie<input name="note" placeholder="Bijv. nalevering verwacht"></label><div class="dialog-actions"><button class="button ghost" type="button" data-close-receipt>Annuleren</button><button class="button primary" type="submit">Scans controleren en boeken</button></div><div id="receiptHistory"></div></form>';document.body.appendChild(dialog);const style=document.createElement('style');style.textContent='.receipt-button{margin:8px 6px 0 0}.receipt-help{color:var(--muted);font-size:11px}.receipt-scan{display:grid;grid-template-columns:auto 1fr;gap:9px;align-items:end;padding:12px;margin:12px 0;background:var(--green-2);border-radius:11px}.receipt-scan label{margin:0}.receipt-scan span{grid-column:1/-1;font-size:10px;color:var(--green);font-weight:700}.receipt-line{display:grid;grid-template-columns:minmax(150px,1fr) 100px 120px;gap:9px;align-items:center;padding:9px 0;border-top:1px solid var(--line)}.receipt-line small{display:block;color:var(--muted)}.receipt-line.scanned{background:#f0fdf4}.receipt-history{margin-top:18px;border-top:1px solid var(--line);padding-top:12px}.receipt-event{display:flex;justify-content:space-between;gap:10px;padding:9px 0;border-bottom:1px solid var(--line)}.receipt-event small{display:block;color:var(--muted)}@media(max-width:580px){.receipt-scan{grid-template-columns:1fr}.receipt-scan span{grid-column:auto}.receipt-line{grid-template-columns:1fr 100px}.receipt-line>span{grid-column:1/-1}.receipt-event{display:block}.receipt-event button{width:100%;margin-top:8px}}';document.head.appendChild(style)}
  async function load(){const result=await Promise.all([api('/api/orders?type=purchase'),api('/api/state')]);orders=result[0].orders||[];state=result[1]||{items:[]};enhance()}
  function enhance(){document.querySelectorAll('[data-order-card-type="purchase"]').forEach(card=>{if(card.querySelector('.receipt-button'))return;const order=orders.find(row=>row.id===card.dataset.orderCardId);if(!order)return;const button=document.createElement('button');button.type='button';button.className='button ghost receipt-button';button.dataset.receiptOrder=order.id;button.textContent=order.status==='received'?'Ontvangsten bekijken':'Ontvangst boeken';card.appendChild(button)})}
  async function open(orderId){active=orders.find(row=>row.id===orderId);if(!active){await load();active=orders.find(row=>row.id===orderId)}if(!active)return;scanCount=0;const receipts=(await api('/api/orders/receipts?order_id='+encodeURIComponent(orderId))).receipts||[];document.getElementById('receiptTitle').textContent=active.order_number||active.reference||'Ontvangst registreren';document.getElementById('receiptLines').innerHTML=active.lines.map(line=>{const remaining=Math.max(0,Number(line.quantity)-Number(line.fulfilled_quantity||0));const item=state.items?.find(item=>String(item.id)===String(line.item_id));return `<label class="receipt-line" data-receipt-item="${esc(line.item_id)}"><span><strong>${esc(line.item_name)}</strong><small>${Number(line.fulfilled_quantity||0).toLocaleString('nl-NL')} ontvangen van ${Number(line.quantity).toLocaleString('nl-NL')} · barcode ${esc(item?.barcode||'niet ingesteld')}</small></span><span>${remaining.toLocaleString('nl-NL')} open</span><input data-receipt-line="${esc(line.id)}" type="number" min="0" max="${remaining}" step="0.001" value="0" ${remaining<=0?'disabled':''}></label>`}).join('');document.getElementById('receiptHistory').innerHTML=`<div class="receipt-history"><strong>Ontvangsthistorie</strong>${receipts.length?receipts.map(receipt=>`<div class="receipt-event"><div><strong>${esc(receipt.reference||'Ontvangst')}</strong><small>${new Date(receipt.received_at).toLocaleString('nl-NL')} · ${esc(receipt.received_by_name||'Onbekend')}</small><small>${receipt.lines.map(line=>`${Number(line.quantity).toLocaleString('nl-NL')}× ${esc(line.item_name)}`).join(' · ')}</small>${receipt.reversed_at?'<small>Teruggedraaid</small>':''}</div>${receipt.reversed_at?'':`<button class="button ghost" type="button" data-reverse-receipt="${receipt.id}">Terugdraaien</button>`}</div>`).join(''):'<p class="receipt-help">Nog geen ontvangsten geregistreerd.</p>'}</div>`;document.getElementById('receiptForm').elements.reference.value='';document.getElementById('receiptForm').elements.note.value='';document.getElementById('receiptScanStatus').textContent='Nog niets gescand.';document.getElementById('receiptBarcodeInput').value='';document.getElementById('receiptDialog').showModal()}
  function applyBarcode(raw){const barcode=String(raw||'').trim(),status=document.getElementById('receiptScanStatus');if(!barcode||!active)return;const item=(state.items||[]).find(row=>String(row.barcode||'').trim()===barcode);if(!item){status.textContent=`Onbekende barcode ${barcode}; niets toegevoegd.`;return}const line=active.lines.find(row=>String(row.item_id)===String(item.id));if(!line){status.textContent=`${item.name} staat niet op deze inkooporder.`;return}const input=document.querySelector(`[data-receipt-line="${CSS.escape(String(line.id))}"]`),next=Number(input?.value||0)+1,max=Number(input?.max||0);if(!input||input.disabled){status.textContent=`${item.name} is al volledig ontvangen.`;return}if(next>max+0.0005){status.textContent=`Te veel gescand: van ${item.name} staan nog ${max.toLocaleString('nl-NL')} open.`;return}input.value=next;input.closest('.receipt-line')?.classList.add('scanned');scanCount++;status.textContent=`${item.name} toegevoegd · ${scanCount} scan${scanCount===1?'':'s'} in deze ontvangst.`}
  async function refresh(){await load();if(active)await open(active.id);document.dispatchEvent(new CustomEvent('orders:refresh'))}
  document.addEventListener('click',async event=>{try{const button=event.target.closest('[data-receipt-order]');if(button){await open(button.dataset.receiptOrder);return}if(event.target.closest('[data-close-receipt]')){active=null;document.getElementById('receiptDialog').close();return}const reverse=event.target.closest('[data-reverse-receipt]');if(reverse&&confirm('Deze ontvangst terugdraaien? De ontvangen voorraad wordt weer afgeboekt.')){const body=new FormData();body.set('receipt_id',reverse.dataset.reverseReceipt);await api('/api/orders/receipt/reverse',{method:'POST',body});await refresh()}}catch(error){alert(error.message)}});
  document.addEventListener('submit',async event=>{if(event.target.id!=='receiptForm')return;event.preventDefault();try{const lines=[...document.querySelectorAll('[data-receipt-line]')].map(input=>({line_id:input.dataset.receiptLine,quantity:Number(input.value)})).filter(line=>line.quantity>0),body=new FormData(event.target);body.set('order_id',active.id);body.set('lines_json',JSON.stringify(lines));await api('/api/orders/receive',{method:'POST',body});await refresh()}catch(error){alert(error.message)}});
  document.addEventListener('keydown',event=>{if(event.target.id!=='receiptBarcodeInput'||event.key!=='Enter')return;event.preventDefault();applyBarcode(event.target.value);event.target.value=''});
  document.addEventListener('stockroom:barcode',event=>{if(event.detail?.target==='receipt')applyBarcode(event.detail.barcode)});
  document.addEventListener('stockroom:refresh',event=>{if(event.detail?.view==='orders')load()});document.addEventListener('orders:refresh',()=>setTimeout(load,50));
  install();load();new MutationObserver(enhance).observe(document.getElementById('purchaseOrders')||document.body,{childList:true,subtree:true});
})();

