(()=>{
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));let importRows=[],importKind='inventory';
async function api(url,options={}){const r=await fetch(url,{cache:'no-store',...options});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Actie mislukt.');return d}
function install(){const settings=document.getElementById('settings');if(!settings||document.getElementById('sessionManagementPanel'))return;const grid=settings.querySelector('.settings-grid');if(!grid)return;const left=grid.children[0]||grid;const right=grid.children[1]||grid;
left.insertAdjacentHTML('beforeend',`<article class="settings-panel" id="importPanel"><h3>Importeren</h3><p>Importeer voorraad, klanten of leveranciers vanuit CSV of Excel. Eerst previewen, daarna pas toepassen.</p><div class="import-controls"><select id="importKind"><option value="inventory">Voorraad</option><option value="customers">Klanten</option><option value="suppliers">Leveranciers</option></select><input id="importFile" type="file" accept=".csv,.xlsx,.xls,text/csv,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"><button class="button ghost" id="previewImport" type="button">Preview</button></div><div id="importPreview"></div><button class="button primary" id="applyImport" type="button" disabled>Importeren</button></article>`);
right.insertAdjacentHTML('afterbegin',`<article class="settings-panel" id="sessionManagementPanel"><h3>Actieve sessies</h3><p>Bekijk waar je account is ingelogd en trek sessies direct in.</p><div id="activeSessions">Laden…</div><button class="button ghost" id="logoutOtherSessions" type="button">Andere apparaten uitloggen</button></article><article class="settings-panel" id="notificationPreferencesPanel"><h3>Notificatievoorkeuren</h3><p>Kies per type of je meldingen in de app en/of per e-mail wilt ontvangen.</p><form id="notificationPreferencesForm"><div id="notificationPreferences"></div><button class="button primary" type="submit">Voorkeuren opslaan</button></form></article>`);
const st=document.createElement('style');st.textContent='.session-row,.pref-row{display:grid;grid-template-columns:1fr auto;gap:10px;align-items:center;padding:10px 0;border-bottom:1px solid var(--line)}.session-row small{display:block;color:var(--muted)}.import-controls{display:grid;grid-template-columns:160px 1fr auto;gap:8px}.import-preview{margin:12px 0;max-height:300px;overflow:auto}.import-preview table{width:100%;border-collapse:collapse}.import-preview td,.import-preview th{padding:7px;border-bottom:1px solid var(--line);text-align:left}.import-errors{color:#991b1b}.pref-options{display:flex;gap:14px;flex-wrap:wrap}.pref-options label{font-weight:500}@media(max-width:700px){.import-controls{grid-template-columns:1fr}.session-row,.pref-row{grid-template-columns:1fr}}';document.head.appendChild(st)}
async function loadSessions(){try{const d=await api('/api/account/sessions');const el=document.getElementById('activeSessions');el.innerHTML=d.sessions.length?d.sessions.map(s=>`<div class="session-row"><div><strong>${s.current?'Dit apparaat':'Actieve sessie'}</strong><small>Aangemeld ${new Date(s.created_at).toLocaleString('nl-NL')} · verloopt ${new Date(s.expires_at).toLocaleString('nl-NL')}</small></div>${s.current?'<span class="role-chip">Huidig</span>':`<button class="button ghost" type="button" data-revoke-session="${esc(s.id)}">Intrekken</button>`}</div>`).join(''):'<small>Geen actieve sessies.</small>'}catch(e){document.getElementById('activeSessions').textContent=e.message}}
const labels={low_stock:'Lage voorraad',unpaid:'Openstaande verkoop',delivery:'Inkomende levering',order:'Orders',system:'Systeemmeldingen'};
async function loadPrefs(){try{const d=await api('/api/account/notification-preferences');document.getElementById('notificationPreferences').innerHTML=d.preferences.map(p=>`<div class="pref-row"><strong>${labels[p.type]||p.type}</strong><div class="pref-options"><label><input type="checkbox" name="${p.type}_in_app" value="1" ${p.in_app?'checked':''}> In app</label><label><input type="checkbox" name="${p.type}_email" value="1" ${p.email?'checked':''}> E-mail</label></div></div>`).join('')}catch(e){document.getElementById('notificationPreferences').textContent=e.message}}
async function rowsFromFile(file){const ext=(file.name.split('.').pop()||'').toLowerCase();if(ext==='csv'){const text=await file.text();const lines=text.replace(/^\uFEFF/,'').split(/\r?\n/).filter(x=>x.trim());if(!lines.length)return[];const parse=line=>{const out=[];let cur='',q=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'){if(q&&line[i+1]==='"'){cur+='"';i++}else q=!q}else if((c===','||c===';')&&!q){out.push(cur);cur=''}else cur+=c}out.push(cur);return out};const heads=parse(lines[0]).map(x=>x.trim());return lines.slice(1).map(line=>{const vals=parse(line),o={};heads.forEach((h,i)=>o[h]=vals[i]??'');return o})}const XLSX=await import('https://cdn.jsdelivr.net/npm/xlsx@0.18.5/+esm');const data=new Uint8Array(await file.arrayBuffer());const wb=XLSX.read(data,{type:'array'});const ws=wb.Sheets[wb.SheetNames[0]];return XLSX.utils.sheet_to_json(ws,{defval:''})}
async function preview(){const file=document.getElementById('importFile').files[0];if(!file)return alert('Kies eerst een CSV- of Excel-bestand.');importKind=document.getElementById('importKind').value;try{importRows=await rowsFromFile(file);const body=new FormData();body.set('kind',importKind);body.set('rows_json',JSON.stringify(importRows));const d=await api('/api/import/preview',{method:'POST',body});const el=document.getElementById('importPreview');el.innerHTML=`<div class="import-preview"><p><strong>${d.valid_count}</strong> geldige rijen · <strong>${d.error_count}</strong> fouten</p>${d.errors.length?`<div class="import-errors">${d.errors.map(x=>`<div>${esc(x)}</div>`).join('')}</div>`:''}${d.rows.length?`<table><thead><tr>${Object.keys(d.rows[0]).slice(0,6).map(k=>`<th>${esc(k)}</th>`).join('')}</tr></thead><tbody>${d.rows.slice(0,20).map(r=>`<tr>${Object.keys(d.rows[0]).slice(0,6).map(k=>`<td>${esc(r[k])}</td>`).join('')}</tr>`).join('')}</tbody></table>`:''}</div>`;document.getElementById('applyImport').disabled=d.error_count>0||d.valid_count===0}catch(e){document.getElementById('importPreview').innerHTML=`<p class="import-errors">${esc(e.message)}</p>`;document.getElementById('applyImport').disabled=true}}
async function applyImport(){if(!confirm(`Deze ${importRows.length} rijen importeren?`))return;const body=new FormData();body.set('kind',importKind);body.set('rows_json',JSON.stringify(importRows));try{const d=await api('/api/import/apply',{method:'POST',body});alert(`${d.imported} rijen geïmporteerd.`);document.getElementById('applyImport').disabled=true;document.getElementById('importPreview').innerHTML='';document.dispatchEvent(new Event('stockroom:refresh'))}catch(e){alert(e.message)}}
document.addEventListener('click',async e=>{try{if(e.target.id==='previewImport')await preview();if(e.target.id==='applyImport')await applyImport();const b=e.target.closest('[data-revoke-session]');if(b&&confirm('Deze sessie intrekken?')){const fd=new FormData();fd.set('session_id',b.dataset.revokeSession);await api('/api/account/sessions/revoke',{method:'POST',body:fd});await loadSessions()}if(e.target.id==='logoutOtherSessions'&&confirm('Alle andere apparaten uitloggen?')){const fd=new FormData();fd.set('all_others','1');await api('/api/account/sessions/revoke',{method:'POST',body:fd});await loadSessions()}}catch(err){alert(err.message)}});
document.addEventListener('submit',async e=>{if(e.target.id!=='notificationPreferencesForm')return;e.preventDefault();try{await api('/api/account/notification-preferences',{method:'POST',body:new FormData(e.target)});alert('Notificatievoorkeuren opgeslagen.');document.dispatchEvent(new Event('stockroom:refresh'))}catch(err){alert(err.message)}});
function init(){install();loadSessions();loadPrefs()}window.addEventListener('load',init);document.addEventListener('click',e=>{if(e.target.closest('[data-view="settings"]'))setTimeout(()=>{loadSessions();loadPrefs()},150)})
})();