(()=>{
const labels={account:'Account',members:'Gebruikers & rollen',documents:'Documenten & facturen',inventory:'Voorraad & barcodes',security:'Beveiliging & notificaties',integrations:'Integraties',billing:'Abonnement & facturatie',advanced:'Overig',danger:'Gevarenzone'};
function category(panel){const t=(panel.querySelector('h3')?.textContent||'').toLowerCase();if(panel.classList.contains('danger-zone')||t.includes('permanent verwijderen'))return'danger';if(t.includes('gebruiker')||t.includes('rollen'))return'members';if(t.includes('mijn account')||t.includes('account'))return'account';if(t.includes('document')||t.includes('factu'))return'documents';if(t.includes('barcode')||t.includes('voorraad')||t.includes('bestel'))return'inventory';if(t.includes('beveilig')||t.includes('sess')||t.includes('notific'))return'security';if(t.includes('integr')||t.includes('smtp')||t.includes('api'))return'integrations';if(t.includes('abonnement')||t.includes('billing')||t.includes('betaling'))return'billing';return'advanced'}
function addToggle(panel){if(panel.dataset.uxReady)return;panel.dataset.uxReady='1';const h=panel.querySelector(':scope>h3');if(!h)return;const head=document.createElement('button');head.type='button';head.className='ux-panel-toggle';head.setAttribute('aria-expanded','true');head.innerHTML=`<span>${h.textContent}</span><span class="ux-chevron">⌄</span>`;h.hidden=true;panel.insertBefore(head,h.nextSibling);head.addEventListener('click',()=>{const collapsed=panel.classList.toggle('ux-collapsed');head.setAttribute('aria-expanded',String(!collapsed))})}
function organize(){const settings=document.getElementById('settings');if(!settings)return;const panels=[...settings.querySelectorAll('.settings-panel')];if(!panels.length)return;panels.forEach(p=>{p.dataset.uxCategory=category(p);addToggle(p)});let bar=document.getElementById('settingsUxBar');if(!bar){bar=document.createElement('div');bar.id='settingsUxBar';bar.className='settings-ux-bar';bar.innerHTML='<label><span>Onderdeel</span><select id="settingsUxSelect"><option value="all">Alles tonen</option></select></label><button type="button" class="button ghost" id="settingsExpandAll">Alles uitklappen</button>';const msg=document.getElementById('settingsMessage');(msg||settings.querySelector('.settings-grid'))?.insertAdjacentElement(msg?'afterend':'beforebegin',bar);bar.querySelector('#settingsUxSelect').addEventListener('change',applyFilter);bar.querySelector('#settingsExpandAll').addEventListener('click',()=>{panelsNow().forEach(p=>p.classList.remove('ux-collapsed'))})}const select=document.getElementById('settingsUxSelect');const current=select.value;const cats=[...new Set(panels.map(p=>p.dataset.uxCategory))];select.innerHTML='<option value="all">Alles tonen</option>'+cats.map(c=>`<option value="${c}">${labels[c]||c}</option>`).join('');if([...select.options].some(o=>o.value===current))select.value=current;applyFilter()}
function panelsNow(){return[...document.querySelectorAll('#settings .settings-panel')]}
function applyFilter(){const value=document.getElementById('settingsUxSelect')?.value||'all';panelsNow().forEach(p=>{p.hidden=value!=='all'&&p.dataset.uxCategory!==value});const grid=document.querySelector('#settings .settings-grid');if(grid)grid.classList.toggle('ux-single-category',value!=='all')}
function style(){if(document.getElementById('siteUxStyle'))return;const s=document.createElement('style');s.id='siteUxStyle';s.textContent=`
#settings .section-head{margin-bottom:12px}.settings-ux-bar{display:flex;gap:10px;align-items:end;justify-content:space-between;margin:0 0 16px;padding:12px 14px;border:1px solid var(--line);border-radius:14px;background:var(--paper)}.settings-ux-bar label{display:grid;gap:5px;min-width:min(320px,100%)}.settings-ux-bar label>span{font-size:12px;font-weight:700;color:var(--muted)}.settings-ux-bar select{width:100%;border:1px solid var(--line);border-radius:10px;padding:10px 12px;background:#fff;font:inherit}.ux-panel-toggle{display:flex;width:100%;align-items:center;justify-content:space-between;gap:12px;border:0;background:transparent;padding:0;margin:0 0 12px;font:inherit;color:var(--ink);font-size:17px;font-weight:800;text-align:left;cursor:pointer}.ux-chevron{font-size:18px;transition:transform .15s ease}.ux-collapsed .ux-chevron{transform:rotate(-90deg)}.ux-collapsed>:not(.ux-panel-toggle):not(h3){display:none!important}.settings-panel{padding:18px!important;margin-bottom:14px!important}.settings-panel>p{margin-bottom:14px!important}.settings-grid{gap:14px!important}.settings-grid.ux-single-category{grid-template-columns:1fr!important}.settings-form,.danger-form,.docv3-grid{gap:10px!important}.settings-panel input,.settings-panel select,.settings-panel textarea,dialog input,dialog select,dialog textarea{min-height:42px}.settings-panel form{max-width:100%}.settings-panel .button,.settings-panel button{min-height:40px}dialog form label{gap:5px}dialog .field-grid{gap:10px}.transaction-fields{gap:10px!important}
@media(max-width:760px){.settings-ux-bar{display:grid;grid-template-columns:1fr}.settings-ux-bar .button{width:100%}.settings-panel{padding:14px!important;border-radius:12px!important}.ux-panel-toggle{font-size:16px}.docv3-actions,.member-actions{display:grid!important;grid-template-columns:1fr}.docv3-actions .button,.member-actions .button{width:100%}}
`;document.head.appendChild(s)}
function navPolish(){const nav=document.querySelector('.sidebar nav');if(!nav||nav.dataset.uxReady)return;nav.dataset.uxReady='1';const settings=nav.querySelector('[data-view="settings"]');if(settings)settings.classList.add('ux-nav-settings')}
document.addEventListener('click',e=>{if(e.target.closest('[data-view="settings"],[data-go="settings"]')){setTimeout(organize,80);setTimeout(organize,350);setTimeout(organize,800)}});window.addEventListener('load',()=>{style();navPolish();setTimeout(organize,500)});
})();