(()=>{
const labels={all:'Alles',account:'Account',members:'Gebruikers & rollen',documents:'Documenten & facturen',inventory:'Voorraad & import',security:'Beveiliging & notificaties',integrations:'Integraties',billing:'Abonnement & facturatie',advanced:'Overig',danger:'Gevarenzone'};
const icons={all:'⌂',account:'○',members:'♙',documents:'▤',inventory:'□',security:'⌾',integrations:'⌁',billing:'€',advanced:'•••',danger:'!'};
function category(panel){const t=(panel.querySelector('h3')?.textContent||'').toLowerCase();if(panel.classList.contains('danger-zone')||t.includes('permanent verwijderen'))return'danger';if(t.includes('gebruiker')||t.includes('rollen'))return'members';if(t.includes('mijn account')||t.includes('account'))return'account';if(t.includes('document')||t.includes('factu'))return'documents';if(t.includes('barcode')||t.includes('voorraad')||t.includes('bestel')||t.includes('import'))return'inventory';if(t.includes('beveilig')||t.includes('sess')||t.includes('notific'))return'security';if(t.includes('integr')||t.includes('smtp')||t.includes('api'))return'integrations';if(t.includes('abonnement')||t.includes('billing')||t.includes('betaling'))return'billing';return'advanced'}
function panelsNow(){return[...document.querySelectorAll('#settings .settings-panel')]}
function addToggle(panel){if(panel.dataset.uxReady)return;panel.dataset.uxReady='1';const h=panel.querySelector(':scope>h3');if(!h)return;const head=document.createElement('button');head.type='button';head.className='ux-panel-toggle';head.setAttribute('aria-expanded','true');head.innerHTML=`<span>${h.textContent}</span><span class="ux-chevron">⌄</span>`;h.hidden=true;panel.insertBefore(head,h.nextSibling);head.addEventListener('click',()=>{const collapsed=panel.classList.toggle('ux-collapsed');head.setAttribute('aria-expanded',String(!collapsed))})}
function setCategory(value='all',scroll=false){const valid=Object.prototype.hasOwnProperty.call(labels,value)?value:'all';panelsNow().forEach(p=>{p.hidden=valid!=='all'&&p.dataset.uxCategory!==valid});const grid=document.querySelector('#settings .settings-grid');if(grid)grid.classList.toggle('ux-single-category',valid!=='all');document.querySelectorAll('[data-settings-category]').forEach(b=>b.classList.toggle('active',b.dataset.settingsCategory===valid));const mobile=document.getElementById('settingsUxSelect');if(mobile&&mobile.value!==valid)mobile.value=valid;document.body.dataset.settingsCategory=valid;if(scroll)document.getElementById('settings')?.scrollIntoView({behavior:'smooth',block:'start'})}
function availableCategories(){const seen=new Set(panelsNow().map(p=>p.dataset.uxCategory));return Object.keys(labels).filter(c=>c==='all'||seen.has(c))}
function buildSettingsNavigation(){const settings=document.getElementById('settings');if(!settings)return;const cats=availableCategories();let bar=document.getElementById('settingsUxBar');if(!bar){bar=document.createElement('div');bar.id='settingsUxBar';bar.className='settings-ux-bar';bar.innerHTML='<div class="settings-ux-heading"><strong>Instellingen</strong><span>Kies een onderdeel</span></div><nav class="settings-category-nav" aria-label="Instellingen onderdelen"></nav><label class="settings-mobile-select"><span>Onderdeel</span><select id="settingsUxSelect"></select></label>';const msg=document.getElementById('settingsMessage');(msg||settings.querySelector('.settings-grid'))?.insertAdjacentElement(msg?'afterend':'beforebegin',bar)}
const nav=bar.querySelector('.settings-category-nav');nav.innerHTML=cats.map(c=>`<button type="button" data-settings-category="${c}"><span>${icons[c]||'•'}</span>${labels[c]}</button>`).join('');nav.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>setCategory(b.dataset.settingsCategory,true)));const select=bar.querySelector('#settingsUxSelect');const current=document.body.dataset.settingsCategory||'all';select.innerHTML=cats.map(c=>`<option value="${c}">${labels[c]}</option>`).join('');select.value=cats.includes(current)?current:'all';select.onchange=()=>setCategory(select.value,true);setCategory(select.value)}
function organize(){const settings=document.getElementById('settings');if(!settings)return;const panels=panelsNow();if(!panels.length)return;panels.forEach(p=>{p.dataset.uxCategory=category(p);addToggle(p)});buildSettingsNavigation();buildSidebarSubmenu()}
function buildSidebarSubmenu(){const nav=document.querySelector('.sidebar nav');const settingsButton=nav?.querySelector('[data-view="settings"]');if(!nav||!settingsButton)return;settingsButton.classList.add('ux-nav-settings');let wrap=document.getElementById('settingsSidebarSubmenu');if(!wrap){wrap=document.createElement('div');wrap.id='settingsSidebarSubmenu';wrap.className='settings-sidebar-submenu';settingsButton.insertAdjacentElement('afterend',wrap)}const cats=availableCategories().filter(c=>c!=='all'&&c!=='danger');wrap.innerHTML=cats.map(c=>`<button type="button" data-settings-sub="${c}">${labels[c]}</button>`).join('');wrap.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>{settingsButton.click();setTimeout(()=>setCategory(b.dataset.settingsSub,true),80)}));settingsButton.onclick=()=>{setTimeout(()=>{organize();wrap.classList.add('open')},60)}}
function polishForms(){document.querySelectorAll('select').forEach(select=>{if(select.dataset.uxSelect)return;select.dataset.uxSelect='1';select.classList.add('ux-select')});document.querySelectorAll('dialog form').forEach(form=>form.classList.add('ux-dialog-form'))}
function style(){if(document.getElementById('siteUxStyle'))return;const s=document.createElement('style');s.id='siteUxStyle';s.textContent=`
#settings .section-head{margin-bottom:14px}.settings-ux-bar{display:grid;grid-template-columns:180px 1fr;gap:14px;margin:0 0 18px;padding:14px;border:1px solid var(--line);border-radius:16px;background:#fff;box-shadow:var(--shadow)}.settings-ux-heading{display:grid;align-content:start;gap:3px;padding:7px 8px}.settings-ux-heading strong{font:800 15px Manrope}.settings-ux-heading span{font-size:10px;color:var(--muted)}.settings-category-nav{display:flex;gap:7px;flex-wrap:wrap}.settings-category-nav button{display:flex;align-items:center;gap:7px;border:1px solid var(--line);background:var(--paper);color:var(--muted);padding:9px 11px;border-radius:10px;font:700 11px 'DM Sans';cursor:pointer}.settings-category-nav button span{font-size:13px}.settings-category-nav button:hover,.settings-category-nav button.active{background:var(--green);border-color:var(--green);color:#fff}.settings-mobile-select{display:none}.ux-panel-toggle{display:flex;width:100%;align-items:center;justify-content:space-between;gap:12px;border:0;background:transparent;padding:0;margin:0 0 12px;font:inherit;color:var(--ink);font-size:17px;font-weight:800;text-align:left;cursor:pointer}.ux-chevron{font-size:18px;transition:transform .15s ease}.ux-collapsed .ux-chevron{transform:rotate(-90deg)}.ux-collapsed>:not(.ux-panel-toggle):not(h3){display:none!important}.settings-panel{padding:18px!important;margin-bottom:14px!important}.settings-panel>p{margin-bottom:14px!important}.settings-grid{gap:14px!important}.settings-grid.ux-single-category{grid-template-columns:1fr!important}.settings-form,.danger-form,.docv3-grid{gap:10px!important}.settings-panel input,.settings-panel select,.settings-panel textarea,dialog input,dialog select,dialog textarea{min-height:42px}.settings-panel form{max-width:100%}.settings-panel .button,.settings-panel button{min-height:40px}.ux-select{appearance:none;background-image:linear-gradient(45deg,transparent 50%,#6f7c75 50%),linear-gradient(135deg,#6f7c75 50%,transparent 50%);background-position:calc(100% - 17px) 50%,calc(100% - 12px) 50%;background-size:5px 5px,5px 5px;background-repeat:no-repeat;padding-right:34px!important}dialog form label{gap:5px}dialog .field-grid{gap:10px}.transaction-fields{gap:10px!important}.ux-dialog-form>label,.ux-dialog-form>.field-grid,.ux-dialog-form>.check-row{margin-top:10px;margin-bottom:10px}.settings-sidebar-submenu{display:none;margin:-2px 0 7px 38px;padding-left:10px;border-left:1px solid rgba(255,255,255,.18)}.settings-sidebar-submenu.open,.ux-nav-settings.active+.settings-sidebar-submenu{display:grid}.settings-sidebar-submenu button{border:0;background:transparent;color:#a9beb5;text-align:left;padding:7px 8px;border-radius:7px;font:600 11px 'DM Sans';cursor:pointer}.settings-sidebar-submenu button:hover{background:rgba(255,255,255,.08);color:#fff}
@media(max-width:900px){.settings-ux-bar{grid-template-columns:1fr}.settings-ux-heading{display:none}.settings-category-nav{display:none}.settings-mobile-select{display:grid;gap:5px;margin:0;font-size:11px}.settings-mobile-select>span{font-weight:700;color:var(--muted)}}
@media(max-width:760px){.settings-ux-bar{padding:10px}.settings-panel{padding:14px!important;border-radius:12px!important}.ux-panel-toggle{font-size:16px}.docv3-actions,.member-actions{display:grid!important;grid-template-columns:1fr}.docv3-actions .button,.member-actions .button{width:100%}.settings-sidebar-submenu{margin-left:30px}}
`;document.head.appendChild(s)}
function refresh(){style();polishForms();organize()}
document.addEventListener('click',e=>{if(e.target.closest('[data-view="settings"],[data-go="settings"]')){setTimeout(refresh,80);setTimeout(refresh,350);setTimeout(refresh,800)}setTimeout(polishForms,0)});window.addEventListener('load',()=>{refresh();setTimeout(refresh,500);setTimeout(refresh,1200)});new MutationObserver(()=>{polishForms();if(document.getElementById('settings'))organize()}).observe(document.documentElement,{childList:true,subtree:true});
})();
