(()=>{
let currentStockroomName='';let currentLogo='';
async function api(url,options={}){const r=await fetch(url,{cache:'no-store',...options});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Actie mislukt.');return d}
function setBrandName(name){if(!name)return;currentStockroomName=name;const brand=document.querySelector('.sidebar .brand');if(!brand)return;let label=brand.querySelector('[data-stockroom-brand-name]');if(!label){label=brand.querySelector('span:last-child');if(label)label.dataset.stockroomBrandName='1'}if(label&&label.textContent!==name)label.textContent=name;if(brand.getAttribute('aria-label')!==`${name} startpagina`)brand.setAttribute('aria-label',`${name} startpagina`)}
function setBrandLogo(data){currentLogo=data||'';const mark=document.querySelector('.sidebar .brand .brand-mark');if(!mark)return;if(currentLogo){if(mark.dataset.logo===currentLogo)return;mark.dataset.logo=currentLogo;mark.textContent='';mark.style.backgroundImage=`url("${currentLogo}")`;mark.style.backgroundSize='contain';mark.style.backgroundPosition='center';mark.style.backgroundRepeat='no-repeat';mark.style.backgroundColor='transparent';mark.style.borderRadius='8px'}else{if(!mark.dataset.logo&&mark.textContent==='S')return;delete mark.dataset.logo;mark.removeAttribute('style');mark.textContent='S'}}
function install(){const panel=[...document.querySelectorAll('#settings .feature-panel')].find(p=>(p.querySelector('h3')?.textContent||'').trim().toLowerCase()==='stockrooms');if(!panel||document.getElementById('renameStockroomForm'))return;const form=document.createElement('form');form.id='renameStockroomForm';form.className='feature-row';form.style.marginTop='16px';form.innerHTML='<input id="renameStockroomName" name="name" required minlength="2" maxlength="120" placeholder="Nieuwe stockroomnaam"><button class="button primary" type="submit">Naam wijzigen</button>';panel.insertBefore(form,panel.querySelector('#createRoomForm')||null)}
async function loadBranding(){try{const d=await api('/api/documents/branding');setBrandLogo(d.logo_data)}catch{}}
async function load(){install();try{const [d]=await Promise.all([api('/api/me'),loadBranding()]);setBrandName(d.stockroom?.name);const input=document.getElementById('renameStockroomName');if(!input)return;input.value=d.stockroom?.name||'';const form=document.getElementById('renameStockroomForm');form.hidden=!['owner','admin'].includes(d.stockroom?.role)}catch{}}
function restoreBrand(){if(currentStockroomName)setBrandName(currentStockroomName);setBrandLogo(currentLogo)}
document.addEventListener('submit',async e=>{if(e.target.id!=='renameStockroomForm')return;e.preventDefault();try{const fd=new FormData(e.target);const d=await api('/api/stockrooms/rename',{method:'POST',body:fd});setBrandName(d.name);alert(`Stockroomnaam gewijzigd naar ${d.name}.`);document.getElementById('settingsStockroomName')?.replaceChildren(document.createTextNode(d.name));document.dispatchEvent(new Event('stockroom:refresh'))}catch(err){alert(err.message)}});
window.addEventListener('load',()=>{setTimeout(load,350);setTimeout(restoreBrand,1200)});document.addEventListener('click',e=>{if(e.target.closest('[data-view="settings"]'))setTimeout(load,180);if(e.target.closest('.nav-item,[data-go]'))setTimeout(restoreBrand,80)});document.addEventListener('stockroom:refresh',()=>{setTimeout(load,0);setTimeout(loadBranding,100)});document.addEventListener('submit',e=>{if(e.target.id==='documentV3Form')setTimeout(loadBranding,700)});document.addEventListener('click',e=>{if(e.target.id==='removeDocLogo')setTimeout(loadBranding,500)});
})();
