(()=>{
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const money=v=>Number(v||0).toLocaleString('nl-NL',{style:'currency',currency:'EUR'});
  const api=async(url,options={})=>{const response=await fetch(url,{credentials:'same-origin',...options}),data=await response.json();if(!response.ok)throw new Error(data.error||'Actie mislukt.');return data};
  let report=null,role='member';const now=new Date();
  function install(){const host=document.getElementById('finance');if(!host||document.getElementById('taxReportPanel'))return;host.insertAdjacentHTML('beforeend',`<article id="taxReportPanel" class="card"><div class="section-heading"><div><p class="eyebrow">Rapportage</p><h2>Btw-overzicht</h2><p>Controleer verschuldigde btw, voorbelasting, correcties en uitzonderingen per kwartaal.</p></div><form id="taxPeriodForm" class="button-row"><input name="year" type="number" min="2000" max="2100" value="${now.getFullYear()}" aria-label="Jaar"><select name="quarter" aria-label="Kwartaal"><option value="1">Q1</option><option value="2">Q2</option><option value="3">Q3</option><option value="4">Q4</option></select><button class="button" type="submit">Tonen</button></form></div><div id="taxSummary"></div><div id="taxExceptions"></div><div id="taxDetails"></div><div id="taxAdjustment"></div></article>`);document.querySelector('#taxPeriodForm [name=quarter]').value=String(Math.floor(now.getMonth()/3)+1)}
  function table(rows,type){return `<div class="table-wrap"><table><thead><tr><th>Datum</th><th>Nummer</th><th>Relatie</th><th>Excl. btw</th><th>Btw</th><th>Totaal</th></tr></thead><tbody>${rows.length?rows.map(row=>`<tr><td>${new Date(row.invoice_date).toLocaleDateString('nl-NL')}</td><td>${esc(row.invoice_number)}</td><td>${esc(row.relation_name||'')}</td><td>${money(row.net)}</td><td>${money(row.vat)}</td><td>${money(row.total)}</td></tr>`).join(''):`<tr><td colspan="6">Geen ${type}facturen in dit kwartaal.</td></tr>`}</tbody></table></div>`}
  function render(){if(!report)return;const summary=document.getElementById('taxSummary'),exceptions=document.getElementById('taxExceptions'),details=document.getElementById('taxDetails'),adjustment=document.getElementById('taxAdjustment');summary.innerHTML=`<div class="metric-grid"><div class="metric"><span>Omzet excl. btw</span><strong>${money(report.summary.turnover)}</strong></div><div class="metric"><span>Verschuldigde btw</span><strong>${money(report.summary.outputVat)}</strong></div><div class="metric"><span>Voorbelasting</span><strong>${money(report.summary.inputVat)}</strong></div><div class="metric"><span>${report.summary.payable>=0?'Te betalen':'Terug te ontvangen'}</span><strong>${money(Math.abs(report.summary.payable))}</strong></div></div><a class="button" href="/api/tax-report/export?year=${report.year}&quarter=${report.quarter}">Accountantsexport downloaden</a>`;exceptions.innerHTML=report.exceptions.length?`<div class="notice warning"><strong>${report.exceptions.length} controlepunt(en)</strong>${report.exceptions.map(item=>`<p>${esc(item.number)} · ${esc(item.message)}</p>`).join('')}</div>`:'<div class="notice success">Geen automatische controlepunten gevonden.</div>';details.innerHTML=`<details open><summary>Verkoopfacturen (${report.sales.length})</summary>${table(report.sales,'verkoop')}</details><details><summary>Inkoopfacturen (${report.purchases.length})</summary>${table(report.purchases,'inkoop')}</details><details><summary>Btw-correcties (${report.adjustments.length})</summary>${report.adjustments.map(row=>`<div class="list-card"><span>${new Date(row.adjustment_date).toLocaleDateString('nl-NL')} · ${row.kind==='output'?'verschuldigd':'voorbelasting'} · ${money(row.vat_amount)} · ${esc(row.reason)}</span>${['owner','admin'].includes(role)?`<button class="button ghost" data-delete-tax="${row.id}">Verwijderen</button>`:''}</div>`).join('')||'<p>Geen handmatige correcties.</p>'}</details>`;adjustment.innerHTML=['owner','admin'].includes(role)?`<details><summary>Btw-correctie toevoegen</summary><form id="taxAdjustmentForm" class="form-grid"><input type="hidden" name="adjustment_date" value="${new Date().toISOString().slice(0,10)}"><label>Type<select name="kind"><option value="output">Verschuldigde btw</option><option value="input">Voorbelasting</option></select></label><label>Bedrag excl. btw<input name="net_amount" type="number" step="0.01" value="0"></label><label>Btw-correctie<input name="vat_amount" type="number" step="0.01" required></label><label>Reden<input name="reason" required></label><button class="button" type="submit">Correctie boeken</button></form></details>`:''}
  async function load(){install();const form=document.getElementById('taxPeriodForm'),year=form.elements.year.value,quarter=form.elements.quarter.value,[me,data]=await Promise.all([api('/api/me'),api(`/api/tax-report?year=${year}&quarter=${quarter}`)]);role=me.stockroom?.role||'member';report=data;render()}
  document.addEventListener('submit',async event=>{try{if(event.target.id==='taxPeriodForm'){event.preventDefault();await load();return}if(event.target.id==='taxAdjustmentForm'){event.preventDefault();await api('/api/tax-adjustments',{method:'POST',body:new FormData(event.target)});await load()}}catch(error){alert(error.message)}});
  document.addEventListener('click',async event=>{const button=event.target.closest('[data-delete-tax]');if(!button||!confirm('Deze btw-correctie verwijderen?'))return;try{const body=new FormData();body.set('adjustment_id',button.dataset.deleteTax);await api('/api/tax-adjustments/delete',{method:'POST',body});await load()}catch(error){alert(error.message)}});
  document.addEventListener('stockroom:refresh',event=>{if(event.detail?.view==='analytics')load()});install();load().catch(()=>{});
})();
