const fs=require('fs'),assert=require('assert');
const html=fs.readFileSync('index.html','utf8');
const css=fs.readFileSync('styles.css','utf8');
assert.doesNotMatch(html,/dashboard-quick-actions/);
assert.doesNotMatch(html,/Snelle acties/);
assert.match(html,/id="quickAddBtn"/);
assert.match(html,/class="table-card inventory-table-card" tabindex="0"/);
assert.match(css,/@media\(max-width:1100px\)/);
assert.match(css,/@media\(max-width:580px\).*\.inventory-metric\{grid-column:1\/-1\}/);
assert.match(css,/\.inventory-table-card:focus-visible/);
console.log('PASS dashboard interface checks');
