const fs=require('fs'),assert=require('assert');
const source=fs.readFileSync('navigation_fit.js','utf8');
assert(source.includes('height:100dvh!important'));
assert(source.includes('position:fixed!important'));
assert(source.includes('min-height:100dvh!important'));
assert(source.includes('overflow-y:auto'));
assert(source.includes("innerHeight<820||visible>8"));
assert(source.includes('@media(max-width:900px)'));
assert(source.includes("closeOtherMenus"));
assert(source.includes('aria-current'));
assert(source.includes('syncActive(nav)'));
assert(source.includes('inset 4px 0 0 #e7c684'));
assert(source.includes('Start & inzicht'));
assert(source.includes('Voorraad & magazijn'));
assert(source.includes('Handel & facturen'));
assert(source.includes('Organisatie & beheer'));
assert(source.includes('function categorize'));
assert(!source.includes("document.addEventListener('pointerover'"));
assert(source.includes("else if(clicked?.closest('.nav-item[data-view],a.nav-item'))closeMenus()"));
assert(source.includes('.trade-sidebar-submenu:not(.open)'));
assert(source.includes('function toggleSettings'));
assert(source.includes('settings-nav-caret'));
assert(source.includes('touch-action:manipulation'));
assert(source.includes("innerWidth<=900)document.querySelector('.sidebar')?.classList.add('open')"));
assert(!source.includes("active.dataset.view!=='settings')closeMenus()"));
console.log('navigation fit checks passed');
